export const EXCHANGE_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  ESCROWED: 'ESCROWED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED_BY_PROVIDER: 'COMPLETED_BY_PROVIDER',
  CONFIRMED: 'CONFIRMED',
  CLOSED: 'CLOSED',
  DECLINED: 'DECLINED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
});
