import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,offerInput,bookingInput} from './helpers.mjs';import {Marketplace} from '../server/marketplace.mjs';import {Payments} from '../server/payments.mjs';import {MockMercadoPago} from '../server/providers/mock.mjs';
async function setup(){const f=fixture();f.m=new Marketplace(f.store,f.legal,f.config);f.g=new MockMercadoPago(f.store,f.config);f.p=new Payments(f.store,f.m,f.legal,f.config,f.g);f.o=f.m.publish('seller',offerInput);f.b=f.m.book('buyer',bookingInput(f,f.o),'once');f.m.accept('seller',f.b.id);await f.p.checkout('buyer',f.b.id,{accept:true,termsHash:f.legal.document.hash});f.a=f.store.one('SELECT * FROM attempts');return f;}
test('ofertas pausadas privadas para el prestador, no para otra cuenta',()=>{const f=fixture(),m=new Marketplace(f.store,f.legal,f.config),o=m.publish('seller',offerInput);m.updateOffer('seller',o.id,{active:false});assert.equal(m.publicOffers('buyer').length,0);assert.equal(m.publicOffers('seller').length,1);f.store.close();});
test('snapshot monetario inmutable aun mediante SQL directo',async()=>{const f=await setup();assert.throws(()=>f.store.run('UPDATE bookings SET price_ars=1000,gross_cents=400000,commission_cents=20000 WHERE id=?',f.b.id));f.store.close();});
test('refrescar token no reactiva los cobros que el prestador pausó',async()=>{const f=await setup();f.p.pauseConnection('seller');f.store.run('UPDATE seller_accounts SET expires_at=0');await f.p.accessToken('seller');assert.equal(f.store.one('SELECT status FROM seller_accounts').status,'PAUSED');f.store.close();});
test('contracargo no se revierte automáticamente con estado posterior contradictorio',async()=>{const f=await setup();const p=f.g.simulate(f.a,'approved');await f.p.reconcilePayment(p.id,'seller');f.advance(1000);f.g.put({...p,status:'charged_back',date_last_updated:new Date(f.store.now()).toISOString()});await f.p.reconcilePayment(p.id,'seller');f.advance(1000);f.g.put({...p,date_last_updated:new Date(f.store.now()).toISOString()});await assert.rejects(f.p.reconcilePayment(p.id,'seller'),{code:'PAYMENT_TERMINAL_REVIEW'});assert.equal(f.m.getBooking('buyer',f.b.id).payment_status,'CHARGED_BACK');f.store.close();});
test('necesidad vinculada respeta la tarifa máxima de quien solicita',()=>{const f=fixture(),m=new Marketplace(f.store,f.legal,f.config),o=m.publish('seller',offerInput);const n=m.publishNeed('buyer',{title:'Necesito ayuda digital',description:'Una tarea de tecnología remota.',category:'Tecnología',maxPriceArs:1000,blocks:4});assert.throws(()=>m.book('buyer',bookingInput(f,o,{needId:n.id}),'need'),{code:'NEED'});assert.equal(f.store.one('SELECT COUNT(*) AS n FROM bookings').n,0);f.store.close();});
test('un reclamo inválido no cambia el estado del servicio',async()=>{const f=await setup();assert.throws(()=>f.m.report('buyer',{bookingId:f.b.id,type:'DISPUTE',body:'x'}));assert.equal(f.m.getBooking('buyer',f.b.id).status,'ACCEPTED');assert.equal(f.store.one('SELECT COUNT(*) AS n FROM reports').n,0);f.store.close();});
test('OAuth vincula state a sesión, consume una sola vez y no expone tokens',async()=>{const f=fixture();f.config.mode='sandbox';f.config.baseUrl='https://beta.example';const m=new Marketplace(f.store,f.legal,f.config);let calls=0;const g={authorizationUrl:(state,challenge)=>`https://auth.mercadopago.com/authorization?state=${state}&challenge=${challenge}`,exchangeCode:async()=>{calls++;return {user_id:9003,access_token:'private-access-token',refresh_token:'private-refresh-token',live_mode:false,expires_in:3600};},me:async()=>({id:9003,site_id:'MLA'})};const p=new Payments(f.store,m,f.legal,f.config,g),result=p.beginOAuth('other','session-a'),state=new URL(result.url).searchParams.get('state');await assert.rejects(p.finishOAuth('other','session-b',state,'code'),{code:'OAUTH_STATE'});assert.equal(calls,0);assert.deepEqual(await p.finishOAuth('other','session-a',state,'code'),{connected:true});await assert.rejects(p.finishOAuth('other','session-a',state,'code'),{code:'OAUTH_STATE'});assert.equal(calls,1);assert.ok(!JSON.stringify(m.bootstrap('other')).includes('private-access-token'));f.store.close();});
