import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {fixture,offerInput,bookingInput} from './helpers.mjs';import {Marketplace} from '../server/marketplace.mjs';import {Payments} from '../server/payments.mjs';import {AuthService} from '../server/auth.mjs';import {MockMercadoPago} from '../server/providers/mock.mjs';import {Worker} from '../server/worker.mjs';import {createHttpServer} from '../server/http.mjs';
async function setup(t){const f=fixture();f.market=new Marketplace(f.store,f.legal,f.config);f.gateway=new MockMercadoPago(f.store,f.config);f.payments=new Payments(f.store,f.market,f.legal,f.config,f.gateway);f.auth=new AuthService(f.store,f.legal,f.config);f.worker=new Worker(f);f.server=createHttpServer(f);await new Promise(r=>f.server.listen(0,'127.0.0.1',r));f.url='http://127.0.0.1:'+f.server.address().port;f.config.baseUrl=f.url;t.after(async()=>{f.worker.stop();await new Promise(r=>f.server.close(r));f.store.close();});f.session=f.auth.createSession('buyer');f.request=(path,method='GET',body,headers={})=>fetch(f.url+path,{method,headers:{cookie:'intera_session='+f.session.token,'content-type':'application/json',origin:f.url,'x-csrf-token':f.session.csrf,...headers},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'manual'});return f;}
test('config sin secretos, sesión saneada y archivos internos inaccesibles',async t=>{const f=await setup(t);let r=await f.request('/api/config');assert.equal(r.status,200);assert.ok(!(await r.text()).includes(f.config.encryptionKey));r=await f.request('/api/session');const s=await r.json();assert.equal(s.user.name,'Ana');assert.ok(!('password_hash' in s.user));for(const path of ['/.env','/server/config.mjs','/data/intera-mock.sqlite','/%2e%2e/server/config.mjs'])assert.equal((await f.request(path)).status,404);});
test('CSRF, origen ajeno y sesión ausente bloquean escrituras',async t=>{const f=await setup(t);assert.equal((await f.request('/api/offers','POST',offerInput,{'x-csrf-token':'wrong'})).status,403);assert.equal((await f.request('/api/offers','POST',offerInput,{origin:'https://attacker.test'})).status,403);assert.equal((await f.request('/api/offers','POST',offerInput,{cookie:''})).status,401);});
test('sin aceptación actual servidor rechaza aunque UI envíe cualquier bandera',async t=>{const f=await setup(t);f.legal.document.hash='new-terms-hash';const r=await f.request('/api/offers','POST',{...offerInput,conditionsAccepted:true});assert.equal(r.status,428);});
test('retorno de checkout no acredita dinero y endpoint privado no expone orden ajena',async t=>{const f=await setup(t);const o=f.market.publish('seller',offerInput),b=f.market.book('buyer',bookingInput(f,o),'1');f.market.accept('seller',b.id);let r=await f.request('/pago/retorno?booking='+b.id+'&status=approved');assert.equal(r.status,303);assert.equal(f.market.getBooking('buyer',b.id).payment_status,'UNPAID');f.session=f.auth.createSession('other');r=await f.request('/api/bookings/'+b.id);assert.equal(r.status,404);});
test('webhook firmado se encola, duplicado deduplicado y GET verifica',async t=>{const f=await setup(t);const o=f.market.publish('seller',offerInput),b=f.market.book('buyer',bookingInput(f,o),'1');f.market.accept('seller',b.id);await f.payments.checkout('buyer',b.id,{accept:true,termsHash:f.legal.document.hash});const p=f.gateway.simulate(f.store.one('SELECT * FROM attempts'));const ts=String(f.store.now()),rid='request-test';const sig=createHmac('sha256',f.config.mpWebhookSecret).update(`id:${p.id};request-id:${rid};ts:${ts};`).digest('hex');const body={type:'payment',data:{id:p.id}},path=`/api/mp/webhook?seller=seller&data.id=${p.id}`;assert.equal((await f.request(path,'POST',body,{'x-signature':'ts='+ts+',v1=bad','x-request-id':rid})).status,401);for(let i=0;i<2;i++)assert.equal((await f.request(path,'POST',body,{'x-signature':`ts=${ts},v1=${sig}`,'x-request-id':rid})).status,200);assert.equal(f.store.one('SELECT count(*) n FROM jobs').n,1);assert.equal(f.market.getBooking('buyer',b.id).payment_status,'CHECKOUT_CREATED');await f.worker.tick();assert.equal(f.market.getBooking('buyer',b.id).payment_status,'APPROVED');});
test('los accesos de simulación no existen fuera de mock',async t=>{const f=await setup(t);f.config.mode='sandbox';assert.equal((await f.request('/api/demo/login','POST',{userId:'seller'})).status,404);assert.equal((await f.request('/api/demo/pay/test','POST',{status:'approved'})).status,404);});
