import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {MercadoPago,verifyWebhook,safeCheckoutUrl} from '../server/providers/mercadopago.mjs';
import {pkce,seal,unseal} from '../server/security.mjs';
const cfg={mpClientId:'1234',mpClientSecret:'private',mode:'sandbox',baseUrl:'https://intera.example',mpWebhookSecret:'secret',webhookMaxAgeSeconds:86400};
test('HMAC exacto, data.id de URL, rechazo de firma/cuerpo alterados y repetición verificable',()=>{
 const ts=String(Math.floor(Date.now()/1000)),rid='req-1',pid='991';const signature=createHmac('sha256','secret').update(`id:${pid};request-id:${rid};ts:${ts};`).digest('hex');
 const headers={'x-signature':`ts=${ts},v1=${signature}`,'x-request-id':rid};
 assert.equal(verifyWebhook(headers,new URL(`https://x?data.id=${pid}`),{data:{id:pid}},cfg).paymentId,pid);
 assert.throws(()=>verifyWebhook({...headers,'x-signature':`ts=${ts},v1=${'0'.repeat(64)}`},new URL(`https://x?data.id=${pid}`),{data:{id:pid}},cfg));
 assert.throws(()=>verifyWebhook(headers,new URL(`https://x?data.id=${pid}`),{data:{id:'992'}},cfg));
 assert.throws(()=>verifyWebhook(headers,new URL('https://x'),{data:{id:pid}},cfg));
});
test('PKCE y cifrado con autenticación y asociación por cuenta',()=>{const p=pkce();assert.ok(p.verifier.length>=43&&p.verifier.length<=128);assert.equal(p.challenge.length,43);const key=Buffer.alloc(32,3).toString('base64');const c=seal({access_token:'secret'},key,'seller-1');assert.ok(!c.includes('secret'));assert.equal(unseal(c,key,'seller-1').access_token,'secret');assert.throws(()=>unseal(c,key,'seller-2'));});
test('URL de checkout solo origen permitido',()=>{assert.equal(safeCheckoutUrl('https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=a'),'https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=a');for(const u of ['javascript:alert(1)','https://mercadopago.com.ar.evil.test/checkout/v1','https://evil.test','http://www.mercadopago.com.ar/checkout/v1'])assert.throws(()=>safeCheckoutUrl(u));});
test('adapter OAuth PKCE y test_token explícito; refresh conserva identidad',async()=>{const calls=[];const mp=new MercadoPago(cfg,async(u,o)=>{calls.push({u,o});return new Response(JSON.stringify({access_token:'token',refresh_token:'refresh',user_id:7,live_mode:false,expires_in:1000}),{status:200});});await mp.exchangeCode('code','verifier');const d=JSON.parse(calls[0].o.body);assert.equal(d.grant_type,'authorization_code');assert.equal(d.code_verifier,'verifier');assert.equal(d.test_token,true);await mp.refresh('refresh');assert.equal(JSON.parse(calls[1].o.body).grant_type,'refresh_token');});
test('Checkout Pro usa token del vendedor y marketplace_fee 5% del bruto',async()=>{const calls=[];const mp=new MercadoPago(cfg,async(u,o)=>{calls.push({u,o});return new Response(JSON.stringify({id:'pref-1',sandbox_init_point:'https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=p'}),{status:200});});const b={id:'booking-1',title:'Inglés',blocks:4,price_ars:2500,gross_cents:1000000,commission_cents:50000,seller_id:'seller'};await mp.createPreference('seller-token',b,{id:'attempt-1',external_ref:'attempt-1',expires_at:Date.now()+3600000},'buyer@example.test');const p=JSON.parse(calls[0].o.body);assert.equal(p.marketplace_fee,500);assert.equal(p.items[0].unit_price,2500);assert.equal(p.items[0].quantity,4);assert.equal(p.items[0].currency_id,'ARS');assert.equal(calls[0].o.headers.Authorization,'Bearer seller-token');assert.equal(p.external_reference,'attempt-1');assert.ok(!('application_fee' in p));});
test('error de crear preferencia no se reintenta automáticamente; no filtra secretos',async()=>{let n=0;const mp=new MercadoPago(cfg,async()=>{n++;return new Response(JSON.stringify({message:'secret-token-private'}),{status:500});});await assert.rejects(mp.createPreference('SECRET',{id:'a',title:'Servicio',blocks:1,price_ars:1000,commission_cents:5000,seller_id:'s'},{id:'b',external_ref:'b',expires_at:Date.now()+3600000},'b@x.test'),e=>!e.message.includes('secret-token'));assert.equal(n,1);});
test('reembolso usa clave estable y ruta del pago',async()=>{const calls=[];const mp=new MercadoPago(cfg,async(u,o)=>{calls.push({u,o});return new Response(JSON.stringify({id:1,status:'approved',amount:1000}),{status:200});});await mp.refund('seller-token','991',100000,'stable-key');assert.ok(calls[0].u.endsWith('/v1/payments/991/refunds'));assert.equal(calls[0].o.headers['X-Idempotency-Key'],'stable-key');assert.equal(JSON.parse(calls[0].o.body).amount,1000);});
test('pago se vincula a la preferencia y aplicación, no solo a una referencia declarada',async()=>{let wrong=false;const responses={'/merchant_orders/21':()=>({id:21,external_reference:'attempt-1',collector:{id:99},application_id:'1234',preference_id:wrong?'another':'pref-1',payments:[{id:991}],total_amount:10000}),'/checkout/preferences/pref-1':()=>({id:'pref-1',external_reference:'attempt-1',collector_id:99,marketplace_fee:500,items:[{currency_id:'ARS',unit_price:2500,quantity:4}],sandbox_init_point:'https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=pref-1'})};const mp=new MercadoPago(cfg,async url=>new Response(JSON.stringify(responses[new URL(url).pathname]()),{status:200}));assert.equal(typeof mp.attestCheckoutPayment,'function');const a={preference_id:'pref-1',external_ref:'attempt-1',mp_seller_id:'99'},b={gross_cents:1000000,commission_cents:50000},p={id:991,order:{id:21,type:'merchant_order'}};assert.equal((await mp.attestCheckoutPayment('seller-token',p,a,b)).id,'pref-1');wrong=true;await assert.rejects(mp.attestCheckoutPayment('seller-token',p,a,b),{code:'PAYMENT_PREFERENCE'});});
