import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,offerInput,bookingInput} from './helpers.mjs';import {Marketplace} from '../server/marketplace.mjs';import {Payments} from '../server/payments.mjs';import {MockMercadoPago} from '../server/providers/mock.mjs';
async function setup(){const f=fixture();f.market=new Marketplace(f.store,f.legal,f.config);f.gateway=new MockMercadoPago(f.store,f.config);f.pay=new Payments(f.store,f.market,f.legal,f.config,f.gateway);f.offer=f.market.publish('seller',offerInput);f.booking=f.market.book('buyer',bookingInput(f,f.offer),'book');f.market.accept('seller',f.booking.id);await f.pay.checkout('buyer',f.booking.id,{accept:true,termsHash:f.legal.document.hash});f.attempt=f.store.one('SELECT * FROM attempts WHERE booking_id=?',f.booking.id);return f;}
async function approved(f,status='approved',overrides={}){const p=f.gateway.simulate(f.attempt,status,overrides);await f.pay.reconcilePayment(p.id,'seller');return p;}
test('cotización en servidor, una sola preferencia bajo concurrencia',async()=>{const f=await setup();await Promise.all(Array.from({length:10},()=>f.pay.checkout('buyer',f.booking.id,{accept:true,termsHash:f.legal.document.hash})));assert.equal(f.store.one('SELECT count(*) n FROM attempts').n,1);assert.equal(f.gateway.created,1);f.store.close();});
test('URL de retorno no se procesa: el pago lo determina GET de MP',async()=>{const f=await setup();assert.equal(f.market.getBooking('buyer',f.booking.id).payment_status,'CHECKOUT_CREATED');await approved(f);assert.equal(f.market.getBooking('buyer',f.booking.id).payment_status,'APPROVED');f.store.close();});
test('pago repetido, ledger de doble entrada y finalización sin mover dinero',async()=>{const f=await setup();const p=await approved(f);await Promise.all(Array.from({length:5},()=>f.pay.reconcilePayment(p.id,'seller')));assert.equal(f.store.one('SELECT count(*) n FROM ledger_entries').n,1);assert.equal(f.store.one('SELECT SUM(cents) n FROM ledger_postings').n,0);f.market.transition('seller',f.booking.id,'start');f.market.transition('seller',f.booking.id,'complete');f.market.transition('buyer',f.booking.id,'confirm');assert.equal(f.store.one('SELECT count(*) n FROM ledger_entries').n,1);f.store.close();});
for(const [name,overrides] of Object.entries({monto:{transaction_amount:1},moneda:{currency_id:'USD'},vendedor:{collector_id:999},referencia:{external_reference:'other'},ambiente:{live_mode:true},comision:{fee_details:[{type:'application_fee',amount:99}]}}))test(`rechaza pago por ${name} incorrecto`,async()=>{const f=await setup();await assert.rejects(approved(f,'approved',overrides));assert.notEqual(f.market.getBooking('buyer',f.booking.id).payment_status,'APPROVED');f.store.close();});
test('rechazado o pendiente no habilita prestación',async()=>{const f=await setup();await approved(f,'pending');assert.throws(()=>f.market.transition('seller',f.booking.id,'start'));await approved(f,'rejected');assert.notEqual(f.market.getBooking('buyer',f.booking.id).payment_status,'APPROVED');f.store.close();});
test('cancelación con pago pide devolución y se confirma con MP',async()=>{const f=await setup();await approved(f);f.market.cancel('buyer',f.booking.id,'No puedo asistir al horario contratado.');const r=f.store.one('SELECT * FROM refunds');assert.equal(r.amount_cents,1000000);await f.pay.executeRefund(r.id);assert.equal(f.market.getBooking('buyer',f.booking.id).payment_status,'REFUNDED');assert.equal(f.store.one('SELECT SUM(cents) n FROM ledger_postings').n,0);await f.pay.executeRefund(r.id);assert.equal(f.gateway.refundCalls,1);f.store.close();});
test('pago tardío de orden cancelada no la reactiva y se devuelve',async()=>{const f=await setup();f.market.cancel('buyer',f.booking.id,'Cancelo antes de realizar el pago.');await approved(f);assert.equal(f.market.getBooking('buyer',f.booking.id).status,'CANCELLED');assert.equal(f.store.one('SELECT count(*) n FROM refunds').n,1);f.store.close();});
test('doble pago real detectado y segundo pago devuelto con clave estable',async()=>{const f=await setup();const p1=await approved(f);const p2=await approved(f);assert.notEqual(p1.id,p2.id);assert.equal(f.store.one('SELECT count(*) n FROM refunds').n,1);assert.equal(f.market.getBooking('buyer',f.booking.id).primary_payment_id,p1.id);await f.pay.executeRefund(f.store.one('SELECT id FROM refunds').id);assert.equal(f.market.getBooking('buyer',f.booking.id).payment_status,'APPROVED');f.store.close();});
test('devolución parcial ajusta comisión por cumulativo sin destruir asientos',async()=>{const f=await setup();const p=await approved(f);const rid=f.market.requestRefund(p.id,250000,'Ajuste parcial autorizado por revisión.','operator:test');await f.pay.executeRefund(rid);assert.equal(f.market.getBooking('buyer',f.booking.id).payment_status,'PARTIALLY_REFUNDED');assert.equal(f.store.one("SELECT SUM(p.cents) n FROM ledger_postings p WHERE account='INTERA_COMMISSION'").n,-37500);assert.throws(()=>f.store.run('DELETE FROM ledger_entries'));f.store.close();});
test('contracargo bloquea operaciones sin presentarlo como devolución voluntaria',async()=>{const f=await setup();const p=await approved(f);f.advance(2000);const data={...p,status:'charged_back',date_last_updated:new Date(f.store.now()).toISOString()};f.gateway.put(data);await f.pay.reconcilePayment(p.id,'seller');assert.equal(f.market.getBooking('buyer',f.booking.id).payment_status,'CHARGED_BACK');assert.throws(()=>f.market.transition('seller',f.booking.id,'start'));f.store.close();});
test('no se degrada un estado con una lectura vieja de MP',async()=>{const f=await setup();const p=await approved(f);f.advance(2000);f.gateway.put({...p,status:'refunded',transaction_amount_refunded:10000,date_last_updated:new Date(f.store.now()).toISOString()});await f.pay.reconcilePayment(p.id,'seller');f.gateway.put(p);await f.pay.reconcilePayment(p.id,'seller');assert.equal(f.market.getBooking('buyer',f.booking.id).payment_status,'REFUNDED');f.store.close();});
test('ampliación tiene tarifa original, requiere pago separado y no cambia el bruto original',async()=>{const f=await setup();await approved(f);const extra=f.market.proposeExtension('seller',f.booking.id,1);assert.equal(extra.gross_cents,250000);assert.equal(extra.commission_cents,12500);assert.equal(extra.payment_status,'UNPAID');assert.equal(f.market.getBooking('buyer',f.booking.id).gross_cents,1000000);f.store.close();});
test('fallo de conexión al crear preferencia queda UNKNOWN y no crea otra',async()=>{const f=fixture();const m=new Marketplace(f.store,f.legal,f.config);const g=new MockMercadoPago(f.store,f.config);let n=0;g.createPreference=async()=>{n++;throw new Error('timeout');};const pay=new Payments(f.store,m,f.legal,f.config,g);const o=m.publish('seller',offerInput),b=m.book('buyer',bookingInput(f,o),'x');m.accept('seller',b.id);const a={accept:true,termsHash:f.legal.document.hash};await assert.rejects(pay.checkout('buyer',b.id,a));await assert.rejects(pay.checkout('buyer',b.id,a));assert.equal(n,1);assert.equal(f.store.one('SELECT status FROM attempts').status,'UNKNOWN');f.store.close();});
test('pago aprobado no significa dinero disponible',async()=>{const f=await setup();await approved(f,'approved',{money_release_status:'pending'});assert.equal(f.market.getBooking('buyer',f.booking.id).payment_status,'APPROVED');assert.equal(f.pay.s.one('SELECT release_status FROM payments').release_status,'pending');f.store.close();});
