import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,offerInput,bookingInput} from './helpers.mjs';import {Marketplace} from '../server/marketplace.mjs';
function setup(){const f=fixture();f.market=new Marketplace(f.store,f.legal,f.config);f.offer=f.market.publish('seller',offerInput);return f;}
test('orden conserva snapshot monetario y solo prestador puede aceptar',()=>{const f=setup();const b=f.market.book('buyer',bookingInput(f,f.offer),'a');assert.equal(b.gross_cents,1000000);assert.equal(b.commission_cents,50000);assert.throws(()=>f.market.accept('buyer',b.id));f.market.accept('seller',b.id);assert.equal(f.market.getBooking('buyer',b.id).status,'ACCEPTED');assert.throws(()=>f.market.getBooking('other',b.id));f.store.close();});
test('rechaza tarifa no permitida, auto contratación y aceptación de quote ausente',()=>{const f=setup();assert.throws(()=>f.market.publish('seller',{...offerInput,priceArs:2000}));assert.throws(()=>f.market.book('seller',bookingInput(f,f.offer),'x'));assert.throws(()=>f.market.book('buyer',bookingInput(f,f.offer,{quoteAccepted:false}),'y'));f.store.close();});
test('precio manipulado o cambiado exige nueva confirmación',()=>{const f=setup();assert.throws(()=>f.market.book('buyer',bookingInput(f,f.offer,{expectedPriceArs:1000}),'x'));const b=f.market.book('buyer',bookingInput(f,f.offer),'b');f.market.updateOffer('seller',f.offer.id,{...offerInput,priceArs:5000});assert.equal(f.market.getBooking('buyer',b.id).price_ars,2500);f.store.close();});
test('idempotencia de reserva ata actor y payload',()=>{const f=setup();const data=bookingInput(f,f.offer);const b=f.market.book('buyer',data,'same');assert.equal(f.market.book('buyer',data,'same').id,b.id);assert.throws(()=>f.market.book('buyer',{...data,blocks:2},'same'));f.store.close();});
test('términos exigidos en servidor y versionados; cancelación permitida sin reaceptar',()=>{const f=setup();const b=f.market.book('buyer',bookingInput(f,f.offer),'b');const changed={...f.legal,accepted:()=>false};const m=new Marketplace(f.store,changed,f.config);assert.throws(()=>m.publish('buyer',offerInput));assert.throws(()=>m.book('buyer',bookingInput(f,f.offer),'c'));m.cancel('buyer',b.id,'Cancelación solicitada antes de iniciar.');assert.equal(m.getBooking('buyer',b.id).status,'CANCELLED');f.store.close();});
test('no double booking entre dos aceptaciones',()=>{const f=setup();const a=f.market.book('buyer',bookingInput(f,f.offer),'a');const b=f.market.book('other',bookingInput(f,f.offer),'b');f.market.accept('seller',a.id);assert.throws(()=>f.market.accept('seller',b.id));f.store.close();});
test('presencial, inicio sin pago y mensajes ajenos bloqueados',()=>{const f=setup();assert.throws(()=>f.market.publish('seller',{...offerInput,modality:'IN_PERSON'}));const b=f.market.book('buyer',bookingInput(f,f.offer),'a');f.market.accept('seller',b.id);assert.throws(()=>f.market.transition('seller',b.id,'start'));assert.throws(()=>f.market.message('other',b.id,'Mensaje privado'));f.market.message('buyer',b.id,'<b>texto, no HTML ejecutable</b>');assert.equal(f.market.details('seller',b.id).messages.length,1);f.store.close();});
test('valoraciones bilaterales no se entregan a otra parte antes de revelar',()=>{const f=setup();const b=f.market.book('buyer',bookingInput(f,f.offer),'a');f.store.run("UPDATE bookings SET status='COMPLETED',payment_status='APPROVED',confirmed_at=? WHERE id=?",f.store.now(),b.id);f.market.review('buyer',b.id,{rating:5,comment:'Muy buena ayuda.'});assert.equal(f.market.details('seller',b.id).reviews.length,0);f.market.review('seller',b.id,{rating:4,comment:'Todo claro.'});assert.equal(f.market.details('seller',b.id).reviews.length,2);f.store.close();});
