import { avatar, badge, button, emptyState, escapeHtml, icon, sectionHeading } from '../components.js';
import { quartersToCt } from '../../domain/ct.js';
import { exchangesForUser } from '../../application/selectors.js';

const STATUS = {
  REQUESTED: ['Propuesta enviada', 'warn'],
  ESCROWED: ['CT reservados', 'positive'],
  IN_PROGRESS: ['En curso', 'positive'],
  COMPLETED_BY_PROVIDER: ['Esperando confirmación', 'warn'],
  CONFIRMED: ['Completado', 'positive'],
  CLOSED: ['Cerrado', 'neutral'],
  DECLINED: ['Rechazado', 'neutral'],
  CANCELLED: ['Cancelado', 'neutral'],
  DISPUTED: ['En disputa', 'warn'],
};

export function renderExchanges({ state }) {
  const user = state.users.find((u) => u.id === state.activeUserId);
  const exchanges = exchangesForUser(state, user.id);
  const active = exchanges.filter((e) => ['REQUESTED','ESCROWED','IN_PROGRESS','COMPLETED_BY_PROVIDER','DISPUTED'].includes(e.status));
  const past = exchanges.filter((e) => !active.includes(e));
  return `<main id="main" class="page container exchanges-page"><div class="page-title-row"><div><span class="eyebrow">Intercambios</span><h1>Acuerdos claros, de punta a punta.</h1><p>Seguí propuestas, créditos reservados, conversaciones y confirmaciones desde un solo lugar.</p></div>${button('Explorar', { href:'#/explorar', tone:'secondary', iconName:'search' })}</div>
    <section class="exchange-group">${sectionHeading('Activos', active.length ? `${active.length} intercambio${active.length>1?'s':''} en movimiento` : 'No tenés intercambios activos')} ${active.length ? `<div class="exchange-list">${active.map((e)=>exchangeRow(state,e,user.id)).join('')}</div>` : emptyState('Todo tranquilo por ahora','Publicá una necesidad o explorá ofertas para iniciar un intercambio.',button('Explorar oportunidades',{href:'#/explorar'}))}</section>
    ${past.length ? `<section class="exchange-group">${sectionHeading('Historial', 'Intercambios anteriores')}<div class="exchange-list">${past.map((e)=>exchangeRow(state,e,user.id)).join('')}</div></section>`:''}
  </main>`;
}

export function renderExchangeDetail({ state, service, exchangeId }) {
  const exchange = state.exchanges.find((e) => e.id === exchangeId);
  if (!exchange) return missing();
  const activeId = state.activeUserId;
  if (![exchange.requesterId,exchange.providerId].includes(activeId)) return `<main id="main" class="page container simple-page"><span class="eyebrow">Intercambio privado</span><h1>No participás de este acuerdo.</h1><p>Cambiá al usuario demo correspondiente para verlo.</p>${button('Ver intercambios',{href:'#/intercambios'})}</main>`;
  const requester = state.users.find((u)=>u.id===exchange.requesterId);
  const provider = state.users.find((u)=>u.id===exchange.providerId);
  const isRequester = activeId===requester.id;
  const counterpart = isRequester ? provider : requester;
  const conversation = state.conversations.find((c)=>c.exchangeId===exchange.id) || {messages:[]};
  const held = service.getBalances(requester.id).held;
  const status = STATUS[exchange.status] || [exchange.status,'neutral'];
  const myReview = state.reviews.find((r)=>r.exchangeId===exchange.id && r.authorId===activeId);
  return `<main id="main" class="page exchange-detail-page"><section class="exchange-top"><div class="container"><a class="back-link" href="#/intercambios">← Intercambios</a><div class="exchange-title"><div><div class="detail-badges">${badge(status[0],status[1])}${badge(exchange.category,'soft')}</div><h1>${escapeHtml(exchange.category)} con ${escapeHtml(counterpart.name)}</h1><p>${isRequester?'Vos solicitaste este intercambio.':'Vos ofrecés el servicio en este intercambio.'} Cada cambio importante queda reflejado en el estado y el ledger.</p></div><div class="exchange-price"><small>Acuerdo</small><strong>${exchange.durationCt} CT</strong><span>${exchange.durationCt*15} minutos</span></div></div></div></section>
    <div class="container exchange-layout"><section class="exchange-main">
      <div class="agreement-card"><div class="agreement-head"><span>${icon('shield',21)}</span><div><small>Resumen acordado</small><strong>Antes de empezar, ambas partes ven lo mismo.</strong></div></div><div class="agreement-grid"><div><small>Solicitante</small><a href="#/perfil/${requester.id}">${escapeHtml(requester.name)}</a></div><div><small>Prestador</small><a href="#/perfil/${provider.id}">${escapeHtml(provider.name)}</a></div><div><small>Modalidad</small><strong>${exchange.modality==='REMOTE'?'Remoto':escapeHtml(exchange.neighborhood)}</strong></div><div><small>Fecha</small><strong>${formatDate(exchange.scheduledAt)}</strong></div></div><div class="escrow-bar ${['ESCROWED','IN_PROGRESS','COMPLETED_BY_PROVIDER','DISPUTED'].includes(exchange.status)?'is-held':''}">${icon('clock',20)}<span>${['ESCROWED','IN_PROGRESS','COMPLETED_BY_PROVIDER','DISPUTED'].includes(exchange.status)?`<strong>${quartersToCt(held)} CT reservados</strong><small>El escrow protege el acuerdo hasta confirmación o resolución.</small>`:exchange.status==='CONFIRMED'?'<strong>CT liberados al prestador</strong><small>El intercambio fue confirmado por el solicitante.</small>':'<strong>Sin reserva activa</strong><small>Los CT se reservan únicamente cuando el prestador acepta.</small>'}</span></div></div>
      ${renderActionPanel({exchange,isRequester,myReview})}
      <div class="chat-card"><div class="chat-head"><div><span class="eyebrow">Conversación local</span><h2>Mensajes con ${escapeHtml(counterpart.name)}</h2></div>${badge('Solo demo','neutral')}</div><div class="messages">${conversation.messages.length?conversation.messages.map((m)=>messageBubble(state,m,activeId)).join(''):`<div class="chat-empty">${icon('message',24)}<p>Todavía no hay mensajes. Usá este espacio para coordinar lo necesario sin salir del flujo.</p></div>`}</div>${!['DECLINED','CANCELLED'].includes(exchange.status)?`<form class="chat-form" data-form="chat"><input type="hidden" name="exchangeId" value="${exchange.id}"><label class="sr-only" for="chat-${exchange.id}">Mensaje</label><input id="chat-${exchange.id}" name="text" maxlength="600" placeholder="Escribí un mensaje…" required><button class="btn btn-primary" type="submit">Enviar</button></form>`:''}</div>
    </section><aside class="exchange-aside"><div class="timeline-card"><span class="eyebrow">Estado</span><h2>Historial del acuerdo</h2><div class="timeline">${exchange.timeline.map((item,index)=>`<div class="timeline-item ${index===exchange.timeline.length-1?'current':''}"><span></span><div><strong>${statusLabel(item.status)}</strong><small>${formatTimestamp(item.at)}</small></div></div>`).join('')}</div></div>${riskCard(exchange)}</aside></div></main>`;
}

function renderActionPanel({exchange,isRequester,myReview}) {
  const id=exchange.id;
  if(exchange.status==='REQUESTED') return `<section class="action-card ${isRequester?'waiting':''}"><span class="action-icon">${icon(isRequester?'clock':'spark',24)}</span><div><span class="eyebrow">Siguiente paso</span><h2>${isRequester?'Esperando a que el prestador responda':'¿Aceptás esta propuesta?'}</h2><p>${isRequester?'Los CT todavía siguen disponibles. Se reservarán recién si la otra persona acepta.':'Al aceptar, la demo valida el saldo del solicitante y reserva los CT en escrow.'}</p>${isRequester?'':`<div class="action-buttons"><button class="btn btn-primary" data-action="accept-exchange" data-exchange-id="${id}">${icon('check',17)} Aceptar y reservar CT</button><button class="btn btn-secondary" data-action="decline-exchange" data-exchange-id="${id}">Rechazar</button></div>`}</div></section>`;
  if(exchange.status==='ESCROWED') return `<section class="action-card"><span class="action-icon">${icon('check',24)}</span><div><span class="eyebrow">Reserva confirmada</span><h2>${exchange.durationCt} CT reservados. Ya pueden empezar.</h2><p>Al iniciar, el acuerdo pasa a “En curso”. No hay cronómetro ni geolocalización continua.</p>${exchange.pendingExtensionCt&&isRequester?`<div class="extension-alert"><strong>Extensión propuesta: +${exchange.pendingExtensionCt} CT</strong><button class="btn btn-secondary" data-action="accept-extension" data-exchange-id="${id}">Aprobar extensión</button></div>`:''}<div class="action-buttons"><button class="btn btn-primary" data-action="start-exchange" data-exchange-id="${id}">Iniciar intercambio</button>${!isRequester?extensionForm(id):''}</div></div></section>`;
  if(exchange.status==='IN_PROGRESS') return `<section class="action-card live"><span class="action-icon">${icon('exchange',24)}</span><div><span class="eyebrow">En curso</span><h2>El intercambio está sucediendo.</h2><p>Si necesitan más tiempo, el prestador propone la extensión y el solicitante debe aprobarla expresamente.</p>${exchange.pendingExtensionCt&&isRequester?`<div class="extension-alert"><strong>Extensión propuesta: +${exchange.pendingExtensionCt} CT</strong><button class="btn btn-secondary" data-action="accept-extension" data-exchange-id="${id}">Aprobar extensión</button></div>`:''}<div class="action-buttons">${isRequester?'<span class="waiting-inline">Esperando finalización del prestador</span>':`<button class="btn btn-primary" data-action="complete-exchange" data-exchange-id="${id}">${icon('check',17)} Marcar como completado</button>${extensionForm(id)}`}</div></div></section>`;
  if(exchange.status==='COMPLETED_BY_PROVIDER') return `<section class="action-card"><span class="action-icon">${icon('check',24)}</span><div><span class="eyebrow">Finalización</span><h2>${isRequester?'¿Recibiste lo acordado?':'Esperando confirmación del solicitante'}</h2><p>${isRequester?'Al confirmar, los CT reservados se liberan al prestador. Si hay un problema, podés abrir una disputa y mantenerlos congelados.':'Los CT continúan en escrow hasta que la contraparte confirme o abra una disputa.'}</p>${isRequester?`<div class="action-buttons"><button class="btn btn-primary" data-action="confirm-exchange" data-exchange-id="${id}">Confirmar y liberar CT</button><button class="btn btn-secondary" data-action="dispute-exchange" data-exchange-id="${id}">Abrir disputa</button></div>`:''}</div></section>`;
  if(exchange.status==='CONFIRMED') return `<section class="action-card done"><span class="action-icon">${icon('check',24)}</span><div><span class="eyebrow">Intercambio confirmado</span><h2>${myReview?'Gracias por valorar el intercambio.':'Tu experiencia ahora puede construir confianza.'}</h2><p>${myReview?'La valoración quedó asociada únicamente a este intercambio real de la demo.':'La reputación y la verificación son capas distintas: pagar/verificar identidad nunca compra reputación.'}</p>${myReview?`<div class="review-done">${icon('check',17)} Valoración enviada</div>`:reviewForm(id,isRequester)}</div></section>`;
  if(exchange.status==='DISPUTED') return `<section class="action-card warning"><span class="action-icon">${icon('info',24)}</span><div><span class="eyebrow">Disputa demo</span><h2>Los CT siguen congelados.</h2><p>En producción este caso pasa a moderación humana. En esta demo no se simula una decisión administrativa para evitar confundirla con un proceso real.</p></div></section>`;
  return `<section class="action-card muted"><span class="action-icon">${icon('info',24)}</span><div><span class="eyebrow">Estado final</span><h2>${statusLabel(exchange.status)}</h2><p>Este acuerdo ya no admite acciones económicas nuevas.</p></div></section>`;
}

function extensionForm(id){return `<form class="inline-extension" data-form="extension"><input type="hidden" name="exchangeId" value="${id}"><label><span class="sr-only">CT extra</span><select name="additionalCt"><option value="1">+1 CT</option><option value="2">+2 CT</option><option value="4">+4 CT</option></select></label><button class="btn btn-secondary" type="submit">Proponer extensión</button></form>`}
function reviewForm(id,isRequester){return `<form class="review-form" data-form="review"><input type="hidden" name="exchangeId" value="${id}">${isRequester?ratingSelect('quality','Calidad percibida'):ratingSelect('clarity','Claridad del pedido')}${ratingSelect('communication','Comunicación')}${ratingSelect('punctuality','Puntualidad')}<label><span>¿Volverías a intercambiar?</span><select name="wouldRepeat"><option value="true">Sí</option><option value="false">No</option></select></label><label class="review-comment"><span>Comentario <small>opcional</small></span><input name="comment" maxlength="500" placeholder="Breve y concreto"></label><button class="btn btn-primary" type="submit">Enviar valoración</button></form>`}
function ratingSelect(name,label){return `<label><span>${label}</span><select name="${name}">${[5,4,3,2,1].map(v=>`<option value="${v}">${v} / 5</option>`).join('')}</select></label>`}
function messageBubble(state,message,activeId){const user=state.users.find(u=>u.id===message.authorId);const mine=message.authorId===activeId;return `<div class="message ${mine?'mine':''}">${mine?'':avatar(user,'sm')}<div><small>${mine?'Vos':escapeHtml(user.name)} · ${formatTimestamp(message.createdAt)}</small><p>${escapeHtml(message.body)}</p></div></div>`}
function exchangeRow(state,e,userId){const other=state.users.find(u=>u.id===(e.requesterId===userId?e.providerId:e.requesterId));const status=STATUS[e.status]||[e.status,'neutral'];return `<a class="exchange-row" href="#/intercambios/${e.id}">${avatar(other)}<span class="exchange-row-main"><small>${e.requesterId===userId?'Solicitaste':'Ofrecés'} · ${escapeHtml(e.category)}</small><strong>${escapeHtml(other.name)}</strong><em>${formatDate(e.scheduledAt)}</em></span><span class="exchange-row-status">${badge(status[0],status[1])}<b>${e.durationCt} CT</b></span>${icon('chevron',17)}</a>`}
function riskCard(exchange){if(!['ESCROWED','IN_PROGRESS'].includes(exchange.status))return `<div class="safety-note">${icon('shield',18)}<span><strong>Modo demo de confianza</strong><small>La identidad y las verificaciones son simuladas. No uses esta demo para coordinar servicios reales.</small></span></div>`;return `<div class="safety-card"><span class="eyebrow">Simular excepciones</span><h3>Trust & Safety</h3><p>Estas acciones existen para probar las reglas económicas. No representan una investigación real.</p><button class="risk-link" data-action="cancel-normal" data-exchange-id="${exchange.id}">Cancelar con 2 h o más <span>100% refund</span></button><button class="risk-link" data-action="cancel-late" data-exchange-id="${exchange.id}">Cancelación tardía solicitante <span>25 / 75</span></button><button class="risk-link" data-action="noshow-requester" data-exchange-id="${exchange.id}">No-show solicitante <span>50 / 50</span></button><button class="risk-link" data-action="noshow-provider" data-exchange-id="${exchange.id}">No-show prestador <span>100% refund</span></button></div>`}
function statusLabel(status){return (STATUS[status]?.[0]||status)}
function formatDate(value){if(!value)return 'A coordinar';const d=new Date(value);return Number.isNaN(d.valueOf())?escapeHtml(value):new Intl.DateTimeFormat('es-AR',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d)}
function formatTimestamp(value){const d=new Date(value);return Number.isNaN(d.valueOf())?'':new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function missing(){return `<main id="main" class="page container simple-page"><span class="eyebrow">No encontrado</span><h1>Intercambio inexistente</h1>${button('Volver',{href:'#/intercambios'})}</main>`}
