import { avatar, badge, button, emptyState, escapeHtml, icon, sectionHeading, stat } from '../components.js';
import { quartersToCt } from '../../domain/ct.js';
import { exchangesForUser } from '../../application/selectors.js';

const CATEGORIES = ['Idiomas', 'Tecnología', 'Diseño', 'Mantenimiento', 'Mascotas', 'Organización', 'Fotografía'];
const NEIGHBORHOODS = ['Almagro', 'Caballito', 'Villa Crespo'];

export function renderExplore({ state }) {
  const activeId = state.activeUserId;
  const offers = state.offers.filter((offer) => offer.active && offer.providerId !== activeId);
  const requests = state.requests.filter((request) => request.status === 'OPEN' && request.requesterId !== activeId);
  return `<main id="main" class="page">
    <section class="page-hero container"><span class="eyebrow">Explorar</span><div class="page-title-row"><div><h1>Explorá lo que la comunidad puede aportar.</h1><p>Encontrá habilidades y necesidades dentro del cluster piloto. Acá no hay precios: hay tiempo, confianza y acuerdos claros.</p></div>${button('Publicar', { href: '#/publicar', iconName: 'plus' })}</div>
      <div class="search-bar">${icon('search', 19)}<input id="explore-search" type="search" placeholder="Buscar por habilidad, necesidad o persona" aria-label="Buscar oportunidades"><button class="btn btn-secondary" type="button" data-action="search-explore">Buscar</button></div>
      <div class="filter-chips" aria-label="Categorías">${['Todo', ...CATEGORIES].map((category, index) => `<button type="button" class="filter-chip ${index === 0 ? 'is-active' : ''}" data-action="filter-category" data-category="${escapeHtml(category)}">${escapeHtml(category)}</button>`).join('')}</div>
    </section>
    <section class="container marketplace-section" data-explore-section>
      ${sectionHeading('Ofertas', `${offers.length} cosas que otras personas pueden hacer por vos`, 'La duración es orientativa y siempre se acuerda antes de reservar CT.')}
      <div class="listing-grid" data-offer-grid>${offers.map((offer) => offerCard(state, offer)).join('')}</div>
    </section>
    <section class="container marketplace-section">
      ${sectionHeading('Necesidades abiertas', 'También podés encontrar a quién ayudar', 'Ayudar suma CT y construye un historial real de contribuciones dentro de la demo.')}
      <div class="needs-list">${requests.map((request) => requestCard(state, request)).join('')}</div>
    </section>
  </main>`;
}

export function renderPublish() {
  return `<main id="main" class="page container form-page"><div class="form-intro"><span class="eyebrow">Publicar</span><h1>¿Qué querés poner en movimiento?</h1><p>INTERA funciona cuando cada persona puede decir con claridad qué puede aportar y qué necesita.</p></div><div class="publish-grid"><a class="publish-card" href="#/ofertas/nueva"><span class="publish-icon">${icon('spark', 28)}</span><span class="eyebrow">Ofrecer</span><h2>Algo que sabés o podés hacer</h2><p>Convertí tu tiempo y una capacidad concreta en Créditos de Tiempo.</p><span class="link-arrow">Crear oferta ${icon('chevron', 16)}</span></a><a class="publish-card" href="#/solicitudes/nueva"><span class="publish-icon alt">${icon('search', 28)}</span><span class="eyebrow">Solicitar</span><h2>Algo que necesitás resolver</h2><p>Contá qué necesitás y encontrá personas compatibles en tu comunidad.</p><span class="link-arrow">Crear solicitud ${icon('chevron', 16)}</span></a></div></main>`;
}

export function renderNewOffer({ state }) {
  const user = state.users.find((u) => u.id === state.activeUserId);
  return `<main id="main" class="page container form-page">${formBack('/publicar')}<div class="form-layout"><section><span class="eyebrow">Nueva oferta</span><h1>¿Qué podés aportar?</h1><p class="lead">Describilo de forma concreta. La otra persona tiene que entender rápido qué recibe y cuánto tiempo reservar.</p>${marketForm({ type: 'offer', user })}</section>${ctAside()}</div></main>`;
}

export function renderNewRequest({ state }) {
  const user = state.users.find((u) => u.id === state.activeUserId);
  return `<main id="main" class="page container form-page">${formBack('/publicar')}<div class="form-layout"><section><span class="eyebrow">Nueva solicitud</span><h1>¿Qué necesitás resolver?</h1><p class="lead">Explicá el resultado que buscás. Después vas a poder elegir entre personas compatibles y proponer un intercambio.</p>${marketForm({ type: 'request', user })}</section>${ctAside()}</div></main>`;
}

export function renderOfferDetail({ state, service, offerId }) {
  const offer = state.offers.find((item) => item.id === offerId);
  if (!offer) return notFound('Oferta no encontrada');
  const provider = state.users.find((u) => u.id === offer.providerId);
  const own = provider.id === state.activeUserId;
  const rep = service.getUserReputation(provider.id);
  const compatibleRequests = state.requests.filter((r) => r.requesterId === state.activeUserId && r.status === 'OPEN' && r.category === offer.category && r.modality === offer.modality);
  return `<main id="main" class="page container detail-page">${formBack('/explorar')}<div class="detail-grid"><section class="detail-main"><div class="detail-badges">${badge(offer.category, 'soft')}${badge(offer.modality === 'REMOTE' ? 'Remoto' : offer.neighborhood, 'neutral')}</div><h1>${escapeHtml(offer.title)}</h1><p class="detail-lead">${escapeHtml(offer.description)}</p><div class="time-quote"><span>${icon('clock', 24)}</span><div><small>Duración típica</small><strong>${offer.durationCt} CT · ${offer.durationCt * 15} minutos</strong><p>El acuerdo final siempre se confirma antes de reservar créditos.</p></div></div><div class="detail-section"><h2>Disponibilidad</h2><p>${escapeHtml(offer.availability)}</p></div><div class="detail-section"><h2>Cómo se intercambia</h2><ol class="step-list"><li><span>1</span>Elegís una necesidad compatible.</li><li><span>2</span>Proponés fecha, duración y modalidad.</li><li><span>3</span>Si ${escapeHtml(provider.name.split(' ')[0])} acepta, los CT quedan reservados.</li></ol></div></section><aside class="profile-aside">${profileMini(provider, rep)}${own ? `<div class="aside-note">Esta oferta es tuya. Cambiá de usuario demo para probarla desde el lado del solicitante.</div>` : compatibleRequests.length ? `<div class="aside-action"><h3>¿Querés pedir esta ayuda?</h3><p>Ya tenés ${compatibleRequests.length} necesidad${compatibleRequests.length > 1 ? 'es' : ''} compatible${compatibleRequests.length > 1 ? 's' : ''}.</p>${compatibleRequests.map((request) => button(`Usar “${request.title}”`, { href: `#/solicitudes/${request.id}`, tone: 'primary' })).join('')}</div>` : `<div class="aside-action"><h3>¿Te sirve esta oferta?</h3><p>Primero publicá qué necesitás. INTERA usa esa necesidad para construir un match trazable.</p>${button('Crear solicitud', { href: '#/solicitudes/nueva', iconName: 'plus' })}</div>`}</aside></div></main>`;
}

export function renderRequestDetail({ state, service, requestId }) {
  const request = state.requests.find((item) => item.id === requestId);
  if (!request) return notFound('Solicitud no encontrada');
  const requester = state.users.find((u) => u.id === request.requesterId);
  const own = requester.id === state.activeUserId;
  const matches = service.findMatches(request.id);
  return `<main id="main" class="page container detail-page">${formBack('/explorar')}<div class="request-hero"><div>${badge(request.status === 'OPEN' ? 'Abierta' : request.status, request.status === 'OPEN' ? 'positive' : 'neutral')}<span class="eyebrow"> ${escapeHtml(request.category)}</span><h1>${escapeHtml(request.title)}</h1><p>${escapeHtml(request.notes || 'Sin notas adicionales.')}</p><div class="request-specs"><span>${icon('clock', 18)} ${request.durationCt} CT · ${request.durationCt * 15} min</span><span>${icon(request.modality === 'REMOTE' ? 'message' : 'map', 18)} ${request.modality === 'REMOTE' ? 'Remoto' : request.neighborhood}</span></div></div><a class="request-owner" href="#/perfil/${requester.id}">${avatar(requester)}<span><small>Solicita</small><strong>${escapeHtml(requester.name)}</strong><small>${escapeHtml(requester.neighborhood)}</small></span>${icon('chevron', 16)}</a></div>
    <section class="matches-section">${sectionHeading('Matching explicable', own ? `${matches.length} personas podrían ayudarte` : 'Así se ve el matching para esta necesidad', own ? 'Elegí una opción y proponé condiciones concretas. Nadie queda reservado hasta que la contraparte acepte.' : 'Solo quien publicó la solicitud puede enviar la propuesta.')}<div class="match-list">${matches.length ? matches.map((match, index) => matchCard(request, match, own, index)).join('') : emptyState('Todavía no hay match', 'Probá otra categoría, modalidad o creá una oferta complementaria.')}</div></section></main>`;
}

export function renderProfile({ state, service, userId }) {
  const user = state.users.find((item) => item.id === userId);
  if (!user) return notFound('Perfil no encontrado');
  const rep = service.getUserReputation(user.id);
  const balances = service.getBalances(user.id);
  const offers = state.offers.filter((o) => o.providerId === user.id && o.active);
  const exchanges = exchangesForUser(state, user.id);
  const isOwn = user.id === state.activeUserId;
  return `<main id="main" class="page"><section class="profile-hero"><div class="container profile-hero-inner">${avatar(user, 'lg')}<div class="profile-identity"><span class="eyebrow">${isOwn ? 'Tu perfil demo' : 'Perfil de la comunidad'}</span><h1>${escapeHtml(user.name)}</h1><p>${escapeHtml(user.bio)}</p><div class="profile-tags">${badge(user.verification === 'V2_DEMO' ? 'Identidad verificada · demo' : 'Perfil básico · demo', user.verification === 'V2_DEMO' ? 'positive' : 'neutral')}${badge(user.neighborhood, 'soft')}</div></div><div class="trust-card"><small>Confianza</small>${rep.stage === 'INDEX' ? `<strong>${rep.index}<span>/100</span></strong>` : `<strong class="building">En construcción</strong>`}<span>${rep.completed} intercambios completados</span></div></div></section><div class="container profile-grid"><section><div class="profile-block"><h2>Lo que puede aportar</h2><div class="skill-pills">${user.skills.map((skill) => `<span>${escapeHtml(skill)}</span>`).join('')}</div></div><div class="profile-block"><h2>Lo que necesita</h2><div class="skill-pills soft">${user.needs.map((skill) => `<span>${escapeHtml(skill)}</span>`).join('')}</div></div>${offers.length ? `<div class="profile-block"><h2>Ofertas activas</h2><div class="profile-offers">${offers.map((offer) => `<a href="#/ofertas/${offer.id}"><span><strong>${escapeHtml(offer.title)}</strong><small>${escapeHtml(offer.category)} · ${offer.modality === 'REMOTE' ? 'Remoto' : offer.neighborhood}</small></span><b>${offer.durationCt} CT</b>${icon('chevron', 16)}</a>`).join('')}</div></div>` : ''}</section><aside><div class="contribution-card"><span class="eyebrow">Historial de contribuciones</span><div class="contribution-stats">${stat('Disponibles', `${quartersToCt(balances.available)} CT`)}${stat('Reservados', `${quartersToCt(balances.held)} CT`)}${stat('Intercambios', String(exchanges.length))}</div><p>${icon('shield', 17)} La verificación mostrada en esta demo es simulada. La reputación se construye únicamente con intercambios confirmados.</p>${isOwn ? button('Ver historial completo', { href: '#/historial', tone: 'secondary' }) : ''}</div></aside></div></main>`;
}

export function renderOnboarding() {
  return `<main id="main" class="page container form-page"><div class="form-layout onboarding-layout"><section><span class="eyebrow">Nuevo perfil demo</span><h1>Traé algo para dar. Contanos qué necesitás.</h1><p class="lead">Este perfil vive solo en tu navegador. Al crearlo recibís 4 CT promocionales para probar el sistema.</p><form class="form-card" data-form="new-profile"><label><span>Nombre y apellido</span><input name="name" required autocomplete="name" placeholder="Ej. Valentina Rossi"></label><div class="form-row"><label><span>Barrio</span><select name="neighborhood" required>${NEIGHBORHOODS.map((n) => `<option>${n}</option>`).join('')}</select></label><label><span>Quiero</span><select name="intent"><option value="BOTH">Ofrecer y solicitar</option><option value="OFFER">Ofrecer</option><option value="REQUEST">Solicitar</option></select></label></div><label><span>Habilidades <small>separadas por coma</small></span><input name="skills" required placeholder="Inglés, Excel, fotografía"></label><label><span>Necesidades <small>separadas por coma</small></span><input name="needs" required placeholder="Soporte tecnológico, diseño"></label><label><span>Sobre vos <small>opcional</small></span><textarea name="bio" rows="3" placeholder="Una frase que ayude a generar contexto y confianza."></textarea></label><button class="btn btn-primary btn-wide" type="submit">Crear perfil y recibir 4 CT ${icon('chevron', 17)}</button></form></section><aside class="onboarding-aside"><span class="balance-icon large">${icon('clock', 32)}</span><h2>4 CT de bienvenida</h2><p>Equivalen a <strong>60 minutos</strong> dentro de la demo.</p><ul><li>${icon('check', 17)} No son dinero ni se pueden comprar.</li><li>${icon('check', 17)} Se reservan cuando alguien acepta tu propuesta.</li><li>${icon('check', 17)} Ganás nuevos CT ayudando a otras personas.</li></ul></aside></div></main>`;
}

export function renderHistory({ state, service }) {
  const user = state.users.find((u) => u.id === state.activeUserId);
  const balances = service.getBalances(user.id);
  const entries = state.ledger.entries.filter((entry) => entry.postings.some((posting) => posting.userId === user.id));
  return `<main id="main" class="page container history-page"><div class="page-title-row"><div><span class="eyebrow">Créditos de Tiempo</span><h1>Tu historial</h1><p>Cada movimiento es append-only: la demo agrega asientos, nunca reescribe saldos anteriores.</p></div></div><div class="history-summary"><div><small>Disponible</small><strong>${quartersToCt(balances.available)} CT</strong></div><div><small>Reservado</small><strong>${quartersToCt(balances.held)} CT</strong></div><div><small>Total de movimientos</small><strong>${entries.length}</strong></div></div><div class="ledger-list">${entries.slice().reverse().map((entry) => { const postings = entry.postings.filter((p) => p.userId === user.id); const netAvailable = postings.filter((p) => p.bucket === 'AVAILABLE').reduce((sum,p)=>sum+p.quarters,0); const netHeld = postings.filter((p)=>p.bucket === 'HELD').reduce((sum,p)=>sum+p.quarters,0); return `<div class="ledger-row"><span class="ledger-icon">${icon(entry.type.includes('HOLD') ? 'clock' : entry.type.includes('RELEASE') ? 'check' : 'exchange', 19)}</span><span><strong>${ledgerLabel(entry.type)}</strong><small>${escapeHtml(entry.metadata?.exchangeId || 'Cuenta demo')} · ${new Date(entry.createdAt).toLocaleDateString('es-AR')}</small></span><span class="ledger-values">${netAvailable ? `<b class="${netAvailable > 0 ? 'credit' : 'debit'}">${netAvailable > 0 ? '+' : ''}${quartersToCt(netAvailable)} CT</b>` : ''}${netHeld ? `<small>${netHeld > 0 ? '+' : ''}${quartersToCt(netHeld)} CT reservados</small>` : ''}</span></div>`; }).join('')}</div></main>`;
}

export function renderHowItWorks() {
  return `<main id="main" class="page"><section class="how-hero container"><span class="eyebrow">Cómo funciona</span><h1>Tu tiempo ya tiene valor.<br>INTERA lo conecta.</h1><p>Una economía circular simple: ayudás a una persona, ganás Créditos de Tiempo y después los usás con alguien distinto.</p></section><section class="container how-steps"><article><span>01</span><h2>Mostrá qué podés aportar</h2><p>Publicá una habilidad concreta con una duración orientativa. No fijás un precio monetario.</p></article><article><span>02</span><h2>Encontrá lo que necesitás</h2><p>INTERA cruza categoría, modalidad y cercanía para mostrar candidatos explicables.</p></article><article><span>03</span><h2>Acordá y reservá CT</h2><p>1 CT = 15 minutos. Cuando el prestador acepta, los créditos quedan en escrow.</p></article><article><span>04</span><h2>Intercambiá, valorá, repetí</h2><p>Al confirmar, los CT pasan al prestador y el intercambio construye reputación verificable.</p></article></section><section class="container equality-banner"><span class="balance-icon large">${icon('clock', 34)}</span><div><span class="eyebrow">Regla central</span><h2>El tiempo de todos vale lo mismo.</h2><p>Una hora de diseño, una hora de conversación o una hora de mantenimiento representan la misma cantidad de CT. La reputación mejora la confianza, no cambia el valor del tiempo.</p></div><strong>4 CT<br><small>= 1 hora</small></strong></section></main>`;
}

function offerCard(state, offer) {
  const provider = state.users.find((u) => u.id === offer.providerId);
  return `<a class="listing-card" href="#/ofertas/${offer.id}" data-category="${escapeHtml(offer.category)}" data-search="${escapeHtml(`${offer.title} ${offer.category} ${provider.name}`.toLowerCase())}"><div class="listing-top"><div>${badge(offer.category, 'soft')}${badge(offer.modality === 'REMOTE' ? 'Remoto' : offer.neighborhood, 'neutral')}</div><strong>${offer.durationCt} CT</strong></div><h3>${escapeHtml(offer.title)}</h3><p>${escapeHtml(offer.description)}</p><div class="listing-person">${avatar(provider, 'sm')}<span><strong>${escapeHtml(provider.name)}</strong><small>${escapeHtml(provider.neighborhood)} · ${provider.verification === 'V2_DEMO' ? 'V2 demo' : 'V1 demo'}</small></span>${icon('chevron', 17)}</div></a>`;
}
function requestCard(state, request) {
  const requester = state.users.find((u) => u.id === request.requesterId);
  return `<a class="need-card" href="#/solicitudes/${request.id}"><span class="need-icon">${icon('search', 19)}</span><span><small>${escapeHtml(request.category)} · ${request.modality === 'REMOTE' ? 'Remoto' : request.neighborhood}</small><strong>${escapeHtml(request.title)}</strong><em>${escapeHtml(requester.name)} · ${escapeHtml(requester.neighborhood)}</em></span><b>${request.durationCt} CT</b>${icon('chevron', 17)}</a>`;
}
function marketForm({ type, user }) {
  const offer = type === 'offer';
  return `<form class="form-card" data-form="new-${type}"><label><span>Título</span><input name="title" required maxlength="80" placeholder="${offer ? 'Ej. Te ayudo a ordenar tu notebook' : 'Ej. Necesito practicar inglés para una entrevista'}"></label><div class="form-row"><label><span>Categoría</span><select name="category" required>${CATEGORIES.map((c) => `<option>${c}</option>`).join('')}</select></label><label><span>Modalidad</span><select name="modality"><option value="REMOTE">Remoto</option><option value="IN_PERSON">Presencial</option></select></label></div><div class="form-row"><label><span>Barrio</span><select name="neighborhood">${NEIGHBORHOODS.map((n) => `<option ${n === user.neighborhood ? 'selected' : ''}>${n}</option>`).join('')}</select></label><label><span>Duración estimada</span><select name="durationCt">${[1,2,4,6,8].map((ct) => `<option value="${ct}" ${ct === 4 ? 'selected' : ''}>${ct} CT · ${ct*15} min</option>`).join('')}</select></label></div><label><span>${offer ? 'Descripción' : 'Notas'}</span><textarea name="${offer ? 'description' : 'notes'}" rows="4" required placeholder="Contá qué incluye, qué esperás y cualquier dato que ayude a acordar."></textarea></label>${offer ? `<label><span>Disponibilidad</span><input name="availability" placeholder="Ej. Martes y jueves después de las 18"></label>` : ''}<button class="btn btn-primary btn-wide" type="submit">${offer ? 'Publicar oferta' : 'Buscar personas compatibles'} ${icon('chevron', 17)}</button></form>`;
}
function ctAside() { return `<aside class="form-aside"><span class="balance-icon large">${icon('clock', 32)}</span><h2>1 CT = 15 minutos</h2><p>Todos los servicios se acuerdan en CT enteros. El tiempo vale lo mismo sin importar la habilidad.</p><div class="ct-examples"><span><b>1 CT</b><small>15 min</small></span><span><b>2 CT</b><small>30 min</small></span><span><b>4 CT</b><small>1 hora</small></span></div><p class="mini-disclaimer">La duración que publicás orienta el match. El acuerdo final queda explícito antes del escrow.</p></aside>`; }
function matchCard(request, match, own, index) { const p=match.provider; return `<article class="full-match-card ${index===0?'top-match':''}"><div class="match-rank"><span>${index===0?'Mejor match':`Opción ${index+1}`}</span><strong>${match.score}%</strong></div><div class="match-profile">${avatar(p)}<div><a href="#/perfil/${p.id}"><strong>${escapeHtml(p.name)}</strong></a><span>${escapeHtml(p.neighborhood)} · ${p.verification==='V2_DEMO'?'Identidad verificada · demo':'Perfil básico · demo'}</span><small>${escapeHtml(match.offer.title)}</small></div></div><div class="reason-pills">${match.reasons.map((reason)=>`<span>${icon('check',13)} ${escapeHtml(reason)}</span>`).join('')}</div><div class="match-offer-summary"><span><small>Duración de su oferta</small><strong>${match.offer.durationCt} CT · ${match.offer.durationCt*15} min</strong></span><a href="#/ofertas/${match.offer.id}">Ver oferta</a></div>${own?`<form class="proposal-form" data-form="propose-exchange"><input type="hidden" name="requestId" value="${request.id}"><input type="hidden" name="offerId" value="${match.offer.id}"><input type="hidden" name="providerId" value="${p.id}"><div class="form-row compact"><label><span>CT a reservar</span><select name="durationCt">${[1,2,4,6,8].map((ct)=>`<option value="${ct}" ${ct===request.durationCt?'selected':''}>${ct} CT · ${ct*15} min</option>`).join('')}</select></label><label><span>Fecha y hora</span><input type="datetime-local" name="scheduledAt" value="2026-09-05T18:00" required></label></div><input type="hidden" name="modality" value="${request.modality}"><label><span>Mensaje <small>opcional</small></span><input name="note" placeholder="Ej. ¿Te sirve este horario?"></label><button class="btn btn-primary btn-wide" type="submit">Proponer intercambio ${icon('chevron',17)}</button></form>`:''}</article>`; }
function profileMini(user, rep) { return `<a class="profile-mini" href="#/perfil/${user.id}">${avatar(user,'lg')}<span class="eyebrow">Prestador</span><h2>${escapeHtml(user.name)}</h2><p>${escapeHtml(user.bio)}</p><div class="profile-mini-meta">${badge(user.verification==='V2_DEMO'?'Identidad verificada · demo':'Perfil básico · demo',user.verification==='V2_DEMO'?'positive':'neutral')}<span>${rep.stage==='INDEX'?`${rep.index}/100 confianza`:'Reputación en construcción'}</span></div><span class="link-arrow">Ver perfil ${icon('chevron',16)}</span></a>`; }
function formBack(path) { return `<a class="back-link" href="#${path}">← Volver</a>`; }
function notFound(title) { return `<main id="main" class="page container simple-page"><span class="eyebrow">No encontrado</span><h1>${escapeHtml(title)}</h1>${button('Volver a explorar',{href:'#/explorar'})}</main>`; }
function ledgerLabel(type) { return ({WELCOME_GRANT:'Créditos de bienvenida',ESCROW_HOLD:'Reserva para intercambio',ESCROW_RELEASE:'Intercambio confirmado',ESCROW_REFUND:'Créditos devueltos',CANCELLATION_PENALTY:'Ajuste por cancelación',NO_SHOW_PENALTY:'Ajuste por inasistencia'}[type]||type); }
