import {id,randomToken,hash,passwordHash,verifyPassword,seal} from './security.mjs';
import {text,ensure} from './domain/errors.mjs';
import {NEIGHBORHOODS} from './marketplace.mjs';
const DUMMY='scrypt$32768$'+ 'a'.repeat(32)+'$'+'0'.repeat(128);
export class AuthService {
 constructor(store,legal,config){this.s=store;this.legal=legal;this.config=config;}
 async register(input,context={}) {
  const name=text(input.name,2,80,'Nombre'),email=text(input.email,5,254,'Correo').toLowerCase();ensure(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),422,'EMAIL','Correo inválido.');
  ensure(typeof input.dob==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(input.dob),422,'ADULT','Ingresá tu fecha de nacimiento.');const dob=new Date(input.dob+'T12:00:00Z'),now=new Date(this.s.now());const age=now.getUTCFullYear()-dob.getUTCFullYear()-((now.getUTCMonth()<dob.getUTCMonth()||(now.getUTCMonth()===dob.getUTCMonth()&&now.getUTCDate()<dob.getUTCDate()))?1:0);ensure(Number.isFinite(dob.getTime())&&dob.toISOString().slice(0,10)===input.dob&&age>=18&&age<=120,422,'ADULT','La plataforma es para personas de 18 años o más.');
  ensure(NEIGHBORHOODS.includes(input.neighborhood),422,'NEIGHBORHOOD','Elegí un barrio válido.');const digest=await passwordHash(input.password);const uid=id();
  return this.s.tx(()=>{ensure(!this.s.one('SELECT id FROM users WHERE email=?',email),409,'EMAIL_EXISTS','Ya existe una cuenta con ese correo. Iniciá sesión o recuperá el acceso.');this.s.run('INSERT INTO users(id,email,password_hash,name,neighborhood,dob,created_at) VALUES(?,?,?,?,?,?,?)',uid,email,digest,name,input.neighborhood,input.dob,this.s.now());this.legal.accept(uid,input.conditions||{},context);return this.s.one('SELECT * FROM users WHERE id=?',uid);});
 }
 createSession(uid){const token=randomToken(),csrf=randomToken();this.s.run('INSERT INTO sessions VALUES(?,?,?,?)',hash(token),uid,csrf,this.s.now()+12*3600000);return {token,csrf};}
 session(token){if(typeof token!=='string'||token.length>150)return null;const row=this.s.one('SELECT * FROM sessions WHERE token_hash=? AND expires_at>?',hash(token),this.s.now());if(!row)return null;const user=this.s.one('SELECT * FROM users WHERE id=?',row.user_id);return user?{...row,user}:null;}
 async login(email,password){const user=typeof email==='string'?this.s.one('SELECT * FROM users WHERE email=?',email.trim().toLowerCase()):null;const valid=await verifyPassword(password,user?.password_hash||DUMMY);ensure(valid&&user,401,'INVALID_LOGIN','Correo o contraseña incorrectos.');this.s.audit(user.id,'LOGIN',user.id);return this.createSession(user.id);}
 logout(token){this.s.run('DELETE FROM sessions WHERE token_hash=?',hash(token));return {ok:true};}
 issueToken(uid,purpose){ensure(['VERIFY','RESET'].includes(purpose),422,'PURPOSE','Acción inválida.');const token=randomToken();this.s.run('INSERT INTO action_tokens VALUES(?,?,?,?,NULL)',hash(token),uid,purpose,this.s.now()+30*60000);return token;}
 useToken(token,purpose){ensure(typeof token==='string'&&token.length<=150,400,'INVALID_TOKEN','Enlace inválido o vencido.');return this.s.tx(()=>{const row=this.s.one('SELECT * FROM action_tokens WHERE token_hash=? AND purpose=? AND used_at IS NULL AND expires_at>?',hash(token),purpose,this.s.now());ensure(row,400,'INVALID_TOKEN','Enlace inválido o vencido.');this.s.run('UPDATE action_tokens SET used_at=? WHERE token_hash=?',this.s.now(),row.token_hash);if(purpose==='VERIFY')this.s.run('UPDATE users SET email_verified=1 WHERE id=?',row.user_id);return row.user_id;});}
 async resetPassword(token,password){const digest=await passwordHash(password);return this.s.tx(()=>{const uid=this.useToken(token,'RESET');this.s.run("UPDATE action_tokens SET used_at=? WHERE user_id=? AND purpose='RESET' AND used_at IS NULL",this.s.now(),uid);this.s.run('UPDATE users SET password_hash=? WHERE id=?',digest,uid);this.s.run('DELETE FROM sessions WHERE user_id=?',uid);this.s.audit(uid,'PASSWORD_RESET',uid);return {ok:true};});}
 sendAction(user,purpose){const token=this.issueToken(user.id,purpose);const url=`${this.config.baseUrl}/#/${purpose==='VERIFY'?'verificar':'recuperar'}/${token}`;if(this.config.mode!=='mock')this.s.enqueue('mail',{encrypted:seal({to:user.email,subject:purpose==='VERIFY'?'Verificá tu correo en INTERA':'Recuperá el acceso a INTERA',text:`Abrí este enlace para continuar: ${url}\nVence en 30 minutos. Si no pediste esta acción, ignorá este mensaje.`},this.config.encryptionKey,'mail')},`mail:${hash(token)}`);return this.config.mode==='mock'?url:null;}
}
