import {ensure,text} from './domain/errors.mjs';
import {quote,PRICE_TIERS} from './domain/pricing.mjs';
import {id,hash} from './security.mjs';
export const CATEGORIES=Object.freeze(['Idiomas','Tecnología','Diseño','Fotografía','Organización','Programación','Redacción']);
export const NEIGHBORHOODS=Object.freeze(['Almagro','Caballito','Villa Crespo','Otro barrio']);
const ACTIVE=['ACCEPTED','IN_PROGRESS','COMPLETED_BY_PROVIDER'];
export class Marketplace {
 constructor(store,legal,config){this.s=store;this.legal=legal;this.config=config;}
 user(userId){const u=this.s.one('SELECT * FROM users WHERE id=?',userId);ensure(u,401,'AUTH','Iniciá sesión.');return u;}
 operate(userId){const u=this.user(userId);ensure(!u.suspended,403,'SUSPENDED','La cuenta tiene operaciones restringidas. Podés consultar y pedir ayuda.');ensure(u.email_verified,403,'VERIFY_EMAIL','Verificá tu correo antes de operar.');ensure(this.legal.accepted(userId),428,'TERMS_REQUIRED','Aceptá las condiciones vigentes antes de operar.');return u;}
 blocked(a,b){return !!this.s.one('SELECT user_id FROM blocks WHERE (user_id=? AND target_id=?) OR (user_id=? AND target_id=?)',a,b,b,a);}
 offer(id){const o=this.s.one('SELECT * FROM offers WHERE id=?',id);ensure(o,404,'NOT_FOUND','No se encontró la publicación.');return o;}
 validateOffer(input){const q=quote(input.priceArs,input.blocks);ensure(CATEGORIES.includes(input.category),422,'CATEGORY','Categoría no habilitada.');ensure(input.modality==='REMOTE',422,'IN_PERSON_DISABLED','Esta entrega habilita únicamente servicios remotos para adultos.');ensure(NEIGHBORHOODS.includes(input.neighborhood),422,'NEIGHBORHOOD','Elegí un barrio válido.');ensure(input.sellerFeeAccepted===true,428,'FEE_ACCEPTANCE','Confirmá la comisión total del 5% y los cargos externos.');return {title:text(input.title,6,100,'Título'),description:text(input.description,20,2000,'Descripción'),category:input.category,modality:'REMOTE',neighborhood:input.neighborhood,availability:text(input.availability||'A coordinar',3,200,'Disponibilidad'),q};}
 publish(userId,input){this.operate(userId);const v=this.validateOffer(input);const oid=id();this.s.tx(()=>{this.s.run('INSERT INTO offers VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',oid,userId,v.title,v.description,v.category,v.modality,v.neighborhood,v.q.priceArs,v.q.blocks,v.availability,1,this.s.now(),this.s.now());this.s.audit(userId,'OFFER_PUBLISHED',oid,{priceArs:v.q.priceArs,commissionBps:500});});return this.offer(oid);}
 updateOffer(userId,oid,input){this.operate(userId);const o=this.offer(oid);ensure(o.provider_id===userId,403,'FORBIDDEN','No podés modificar esta publicación.');if(Object.keys(input).length===1&&typeof input.active==='boolean'){this.s.run('UPDATE offers SET active=?,updated_at=? WHERE id=?',Number(input.active),this.s.now(),oid);return this.offer(oid);}const v=this.validateOffer(input);this.s.run('UPDATE offers SET title=?,description=?,category=?,modality=?,neighborhood=?,price_ars=?,blocks=?,availability=?,updated_at=? WHERE id=?',v.title,v.description,v.category,v.modality,v.neighborhood,v.q.priceArs,v.q.blocks,v.availability,this.s.now(),oid);this.s.audit(userId,'OFFER_UPDATED',oid,{priceArs:v.q.priceArs});return this.offer(oid);}
 publishNeed(userId,input){const u=this.operate(userId);quote(input.maxPriceArs,input.blocks);ensure(CATEGORIES.includes(input.category),422,'CATEGORY','Categoría no habilitada.');const nid=id();this.s.run('INSERT INTO needs VALUES(?,?,?,?,?,?,?,?,?,?)',nid,userId,text(input.title,6,100,'Título'),text(input.description,10,1500,'Descripción'),input.category,u.neighborhood,input.maxPriceArs,input.blocks,1,this.s.now());return this.s.one('SELECT * FROM needs WHERE id=?',nid);}
 closeNeed(userId,nid){this.operate(userId);ensure(this.s.one('SELECT id FROM needs WHERE id=? AND user_id=?',nid,userId),403,'FORBIDDEN','Solicitud no disponible.');this.s.run('UPDATE needs SET active=0 WHERE id=?',nid);return {ok:true};}
 getBooking(userId,bid){this.user(userId);const b=this.s.one('SELECT b.*,u.name AS seller_name,v.name AS buyer_name FROM bookings b JOIN users u ON u.id=b.seller_id JOIN users v ON v.id=b.buyer_id WHERE b.id=?',bid);ensure(b&&[b.seller_id,b.buyer_id].includes(userId),404,'NOT_FOUND','Orden no disponible.');return b;}
 assertConnection(sellerId){const a=this.s.one("SELECT * FROM seller_accounts WHERE user_id=? AND status='CONNECTED' AND mode=?",sellerId,this.config.mode);ensure(a,409,'CONNECT_MP','El prestador debe vincular su cuenta de Mercado Pago antes de recibir contrataciones.');return a;}
 insertBooking(data){const {buyerId,sellerId,offerId,needId=null,parentId=null,kind='SERVICE',title,category,modality,neighborhood,q,scheduledAt,notes='',status='REQUESTED'}=data;
   const bid=id(),now=this.s.now();this.s.run('INSERT INTO bookings(id,offer_id,buyer_id,seller_id,need_id,parent_id,kind,title,category,modality,neighborhood,price_ars,blocks,gross_cents,commission_cents,terms_hash,scheduled_at,end_at,status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',bid,offerId,buyerId,sellerId,needId,parentId,kind,title,category,modality,neighborhood,q.priceArs,q.blocks,q.grossCents,q.commissionCents,this.legal.document.hash,scheduledAt,scheduledAt+q.minutes*60000,status,notes,now,now);return bid;
 }
 book(userId,input,key){return this.s.tx(()=>{
   this.operate(userId);ensure(typeof key==='string'&&key.length>0&&key.length<=150,422,'IDEMPOTENCY','Falta identificador de solicitud.');const k=`${userId}:book:${key}`,digest=hash(JSON.stringify(input));const prev=this.s.one('SELECT * FROM request_keys WHERE key=?',k);if(prev){ensure(prev.payload_hash===digest,409,'IDEMPOTENCY_CONFLICT','El identificador ya se usó con otros datos.');return this.getBooking(userId,prev.result_id);}
   const o=this.offer(input.offerId);ensure(o.active&&o.provider_id!==userId,422,'OFFER_UNAVAILABLE','La publicación no está disponible para esta cuenta.');this.operate(o.provider_id);this.assertConnection(o.provider_id);ensure(!this.blocked(userId,o.provider_id),403,'BLOCKED','No se puede contratar entre estas cuentas.');
   ensure(input.quoteAccepted===true&&input.termsHash===this.legal.document.hash,428,'QUOTE_ACCEPTANCE','Confirmá el precio, duración y condiciones de la orden.');ensure(input.expectedPriceArs===o.price_ars,409,'PRICE_CHANGED','La tarifa cambió. Revisá la cotización antes de confirmar.');const q=quote(o.price_ars,input.blocks);
   ensure(typeof input.scheduledAt==='string'&&/(Z|[+-]\d{2}:\d{2})$/.test(input.scheduledAt),422,'DATE','La fecha debe incluir zona horaria.');const at=Date.parse(input.scheduledAt);ensure(Number.isFinite(at)&&at>=this.s.now()+300000&&at<=this.s.now()+90*86400000,422,'DATE','Elegí un horario futuro dentro de 90 días.');
   if(input.needId){const n=this.s.one('SELECT * FROM needs WHERE id=?',input.needId);ensure(n&&n.user_id===userId&&n.active&&n.category===o.category&&n.max_price_ars>=o.price_ars,422,'NEED','Necesidad no compatible.');}
   const bid=this.insertBooking({buyerId:userId,sellerId:o.provider_id,offerId:o.id,needId:input.needId||null,title:o.title,category:o.category,modality:o.modality,neighborhood:o.neighborhood,q,scheduledAt:at,notes:text(input.notes||'',0,1500,'Notas')});
   this.s.run('INSERT INTO request_keys VALUES(?,?,?,?)',k,userId,digest,bid);this.s.audit(userId,'BOOKING_REQUESTED',bid,{grossCents:q.grossCents,commissionCents:q.commissionCents});return this.getBooking(userId,bid);
 });}
 assertSlot(b){const conflict=this.s.one("SELECT id FROM bookings WHERE id<>? AND (seller_id IN (?,?) OR buyer_id IN (?,?)) AND status IN ('ACCEPTED','IN_PROGRESS','COMPLETED_BY_PROVIDER') AND scheduled_at<? AND end_at>? AND (payment_status='APPROVED' OR payment_deadline>?) LIMIT 1",b.id,b.seller_id,b.buyer_id,b.seller_id,b.buyer_id,b.end_at,b.scheduled_at,this.s.now());ensure(!conflict,409,'TIME_CONFLICT','El horario se superpone con otro acuerdo aceptado.');}
 accept(userId,bid){return this.s.tx(()=>{this.operate(userId);const b=this.getBooking(userId,bid);ensure(b.seller_id===userId,403,'ROLE','Solo el prestador puede aceptar.');if(b.status==='ACCEPTED')return b;ensure(b.status==='REQUESTED'&&b.scheduled_at>this.s.now()+60000,409,'STATE','La solicitud ya no se puede aceptar.');this.operate(b.buyer_id);ensure(!this.blocked(b.buyer_id,b.seller_id),403,'BLOCKED','Estas cuentas no pueden operar entre sí.');this.assertConnection(userId);this.assertSlot(b);if(b.need_id)ensure(!this.s.one("SELECT id FROM bookings WHERE need_id=? AND id<>? AND status NOT IN ('REQUESTED','CANCELLED')",b.need_id,b.id),409,'NEED_RESERVED','La necesidad ya tiene una orden aceptada.');this.s.run("UPDATE bookings SET status='ACCEPTED',payment_deadline=?,updated_at=? WHERE id=?",Math.min(this.s.now()+86400000,b.scheduled_at),this.s.now(),bid);this.s.audit(userId,'BOOKING_ACCEPTED',bid);return this.getBooking(userId,bid);});}
 transition(userId,bid,action){return this.s.tx(()=>{this.operate(userId);const b=this.getBooking(userId,bid);ensure(b.payment_status==='APPROVED',409,'PAYMENT_REQUIRED','Se necesita un pago aprobado y sin devolución o disputa de pago.');const rule={start:['ACCEPTED','IN_PROGRESS','seller_id','started_at'],complete:['IN_PROGRESS','COMPLETED_BY_PROVIDER','seller_id','completed_at'],confirm:['COMPLETED_BY_PROVIDER','COMPLETED','buyer_id','confirmed_at']}[action];ensure(rule,422,'ACTION','Acción inválida.');ensure(b[rule[2]]===userId,403,'ROLE','Esta acción corresponde a la otra parte.');if(b.status===rule[1])return b;ensure(b.status===rule[0],409,'STATE','El estado no permite esta acción.');if(action==='start'&&this.config.mode!=='mock')ensure(this.s.now()>=b.scheduled_at-15*60000,409,'TOO_EARLY','El inicio se habilita 15 minutos antes del horario acordado.');this.s.run(`UPDATE bookings SET status=?,${rule[3]}=?,updated_at=? WHERE id=?`,rule[1],this.s.now(),this.s.now(),bid);this.s.audit(userId,`SERVICE_${action.toUpperCase()}`,bid,{movesMoney:false});return this.getBooking(userId,bid);});}
 proposeExtension(userId,bid,blocks){return this.s.tx(()=>{this.operate(userId);const p=this.getBooking(userId,bid);ensure(p.seller_id===userId&&!p.parent_id&&['ACCEPTED','IN_PROGRESS'].includes(p.status)&&p.payment_status==='APPROVED',409,'EXTENSION','Solo el prestador puede proponer una ampliación de un servicio activo y pagado.');const children=this.s.all("SELECT * FROM bookings WHERE parent_id=? AND status<>'CANCELLED'",p.id);ensure(p.blocks+children.reduce((a,b)=>a+b.blocks,0)+blocks<=32,422,'MAX_BLOCKS','Una prestación admite hasta 32 bloques en total.');const q=quote(p.price_ars,blocks);const start=Math.max(p.end_at,...children.map(c=>c.end_at));const child=this.insertBooking({buyerId:p.buyer_id,sellerId:p.seller_id,offerId:p.offer_id,parentId:p.id,kind:'EXTENSION',title:'Ampliación · '+p.title,category:p.category,modality:p.modality,neighborhood:p.neighborhood,q,scheduledAt:start,status:'ACCEPTED',notes:'Ampliación propuesta; no autorizada hasta que el solicitante acepte el precio e ingrese un pago aprobado.'});const b=this.getBooking(userId,child);this.assertSlot(b);this.s.run('UPDATE bookings SET payment_deadline=? WHERE id=?',Math.max(this.s.now()+15*60000,Math.min(start,this.s.now()+86400000)),child);this.s.audit(userId,'EXTENSION_PROPOSED',child,{parentId:p.id,blocks});return this.getBooking(userId,child);});}
 requestRefund(paymentId,amountCents,reason,actor){return this.s.tx(()=>{const p=this.s.one('SELECT * FROM payments WHERE id=?',paymentId);ensure(p&&['approved','refunded'].includes(p.status),409,'REFUND','Pago no reembolsable.');ensure(Number.isSafeInteger(amountCents)&&amountCents>0,422,'AMOUNT','Importe de devolución inválido.');const pending=this.s.one("SELECT COALESCE(SUM(amount_cents),0) AS amount FROM refunds WHERE payment_id=? AND status IN ('REQUESTED','PROCESSING','SUBMITTED')",paymentId).amount;ensure(amountCents<=p.amount_cents-p.refunded_cents-pending,409,'REFUND_LIMIT','La devolución excede el importe restante o ya está solicitada.');const rid=id();this.s.run('INSERT INTO refunds(id,booking_id,payment_id,amount_cents,reason,actor,status,idempotency_key,mp_refund_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',rid,p.booking_id,paymentId,amountCents,text(reason,10,1500,'Motivo'),actor,'REQUESTED',id(),null,this.s.now(),this.s.now());this.s.enqueue('refund',{refundId:rid},`refund:${rid}`);this.s.run("UPDATE bookings SET payment_status='REFUND_PENDING' WHERE id=?",p.booking_id);this.s.audit(actor,'REFUND_REQUESTED',p.booking_id,{refundId:rid,amountCents});return rid;});}
 cancel(userId,bid,reason){return this.s.tx(()=>{this.user(userId);const b=this.getBooking(userId,bid);if(b.status==='CANCELLED')return b;ensure(['REQUESTED','ACCEPTED'].includes(b.status),409,'OPEN_CLAIM','El servicio ya se inició. Abrí un reclamo para solicitar revisión.');const note=text(reason,10,1500,'Motivo');const rows=[b,...this.s.all("SELECT * FROM bookings WHERE parent_id=? AND status IN ('REQUESTED','ACCEPTED')",b.id)];for(const row of rows){this.s.run("UPDATE bookings SET status='CANCELLED',cancel_reason=?,updated_at=? WHERE id=?",note,this.s.now(),row.id);const a=this.s.one('SELECT * FROM attempts WHERE booking_id=?',row.id);if(a)this.s.enqueue('expire_preference',{attemptId:a.id},`expire:${a.id}`);for(const p of this.s.all("SELECT * FROM payments WHERE booking_id=? AND status='approved'",row.id)){const pending=this.s.one("SELECT COALESCE(SUM(amount_cents),0) AS amount FROM refunds WHERE payment_id=? AND status IN ('REQUESTED','PROCESSING','SUBMITTED')",p.id).amount;const remaining=p.amount_cents-p.refunded_cents-pending;if(remaining>0)this.requestRefund(p.id,remaining,note,userId);}this.s.audit(userId,'BOOKING_CANCELLED',row.id,{reason:note});}return this.getBooking(userId,bid);});}
 message(userId,bid,body){this.operate(userId);this.getBooking(userId,bid);const mid=id();this.s.run('INSERT INTO messages VALUES(?,?,?,?,?)',mid,bid,userId,text(body,1,2000,'Mensaje'),this.s.now());return {id:mid};}
 review(userId,bid,input){this.operate(userId);const b=this.getBooking(userId,bid);ensure(b.status==='COMPLETED'&&b.payment_status==='APPROVED',409,'REVIEW_STATE','Solo se valora un servicio completado y pagado.');ensure(Number.isInteger(input.rating)&&input.rating>=1&&input.rating<=5,422,'RATING','Elegí una valoración de 1 a 5.');ensure(!this.s.one('SELECT id FROM reviews WHERE booking_id=? AND author_id=?',bid,userId),409,'REVIEW_EXISTS','Ya enviaste tu valoración.');this.s.run('INSERT INTO reviews VALUES(?,?,?,?,?,?,?)',id(),bid,userId,b.buyer_id===userId?b.seller_id:b.buyer_id,input.rating,text(input.comment||'',0,1000,'Comentario'),this.s.now());return {ok:true};}
 report(userId,input){return this.s.tx(()=>{this.user(userId);const body=text(input.body,10,3000,'Descripción'),type=text(input.type||'OTHER',3,50,'Tipo');if(input.bookingId)this.getBooking(userId,input.bookingId);const rid=id();if(type==='DISPUTE'&&input.bookingId){const b=this.getBooking(userId,input.bookingId);ensure(!['REQUESTED','CANCELLED'].includes(b.status),409,'STATE','La orden no admite una disputa; podés reportar otro problema.');this.s.run("UPDATE bookings SET status='DISPUTED',updated_at=? WHERE id=?",this.s.now(),b.id);}this.s.run('INSERT INTO reports(id,user_id,booking_id,subject_id,type,body,created_at) VALUES(?,?,?,?,?,?,?)',rid,userId,input.bookingId||null,input.subjectId||null,type,body,this.s.now());this.s.audit(userId,'REPORT_OPENED',rid,{type,bookingId:input.bookingId||null});return {id:rid,status:'OPEN'};});}
 toggleFavorite(userId,oid){this.operate(userId);this.offer(oid);const row=this.s.one('SELECT * FROM favorites WHERE user_id=? AND offer_id=?',userId,oid);if(row)this.s.run('DELETE FROM favorites WHERE user_id=? AND offer_id=?',userId,oid);else this.s.run('INSERT INTO favorites VALUES(?,?)',userId,oid);return {saved:!row};}
 toggleBlock(userId,target){this.user(userId);this.user(target);ensure(userId!==target,422,'SELF','No podés bloquearte.');const row=this.s.one('SELECT * FROM blocks WHERE user_id=? AND target_id=?',userId,target);if(row)this.s.run('DELETE FROM blocks WHERE user_id=? AND target_id=?',userId,target);else this.s.run('INSERT INTO blocks VALUES(?,?)',userId,target);return {blocked:!row};}
 profile(userId,input){this.operate(userId);ensure(NEIGHBORHOODS.includes(input.neighborhood),422,'NEIGHBORHOOD','Barrio inválido.');this.s.run('UPDATE users SET name=?,bio=?,neighborhood=? WHERE id=?',text(input.name,2,80,'Nombre'),text(input.bio||'',0,1000,'Descripción'),input.neighborhood,userId);return this.safeUser(this.user(userId));}
 safeUser(u){return {id:u.id,name:u.name,neighborhood:u.neighborhood,bio:u.bio,is_demo:!!u.is_demo};}
 details(userId,bid){const b=this.getBooking(userId,bid);const rev=this.s.all('SELECT * FROM reviews WHERE booking_id=?',bid);const revealed=rev.length>=2||(b.confirmed_at&&this.s.now()-b.confirmed_at>=7*86400000);return {booking:b,messages:this.s.all('SELECT m.*,u.name AS sender_name FROM messages m JOIN users u ON u.id=m.sender_id WHERE booking_id=? ORDER BY created_at DESC LIMIT 200',bid).reverse(),reviews:rev.filter(r=>revealed||r.author_id===userId),reviewsRevealed:!!revealed,payments:this.s.all('SELECT * FROM payments WHERE booking_id=? ORDER BY updated_at DESC',bid),refunds:this.s.all('SELECT id,amount_cents,status,reason,created_at FROM refunds WHERE booking_id=?',bid),children:this.s.all('SELECT id,title,status,payment_status,blocks,gross_cents FROM bookings WHERE parent_id=?',bid),reports:this.s.all('SELECT id,type,status,body,resolution,created_at FROM reports WHERE user_id=? AND booking_id=?',userId,bid)};}
 publicOffers(userId=null){return this.s.all("SELECT o.*,u.name AS provider_name,u.is_demo,u.bio,CASE WHEN a.status='CONNECTED' THEN 1 ELSE 0 END AS connected FROM offers o JOIN users u ON u.id=o.provider_id LEFT JOIN seller_accounts a ON a.user_id=u.id WHERE u.suspended=0 ORDER BY o.created_at DESC").filter(o=>userId? (o.active||o.provider_id===userId)&&!this.blocked(userId,o.provider_id):o.active).map(o=>({...o,ready:!!o.connected&&this.legal.accepted(o.provider_id)}));}
 bootstrap(userId){const u=userId?this.user(userId):null;return {offers:this.publicOffers(userId),people:this.s.all('SELECT id,name,neighborhood,bio,is_demo FROM users WHERE suspended=0'),needs:this.s.all('SELECT n.*,u.name AS requester_name FROM needs n JOIN users u ON n.user_id=u.id WHERE n.active=1'),bookings:u?this.s.all('SELECT b.*,u.name AS seller_name,v.name AS buyer_name FROM bookings b JOIN users u ON u.id=b.seller_id JOIN users v ON v.id=b.buyer_id WHERE b.buyer_id=? OR b.seller_id=? ORDER BY b.created_at DESC',userId,userId):[],favorites:u?this.s.all('SELECT offer_id FROM favorites WHERE user_id=?',userId).map(r=>r.offer_id):[],seller:u?this.s.one('SELECT mp_user_id,status,mode,updated_at FROM seller_accounts WHERE user_id=?',userId):null,conditionsAccepted:u?this.legal.accepted(userId):false,categories:CATEGORIES,neighborhoods:NEIGHBORHOODS,priceTiers:PRICE_TIERS};}
 finances(userId){this.user(userId);return {payments:this.s.all('SELECT p.*,b.title,b.seller_id,b.buyer_id,b.commission_cents AS agreed_commission_cents,b.gross_cents FROM payments p JOIN bookings b ON b.id=p.booking_id WHERE b.seller_id=? OR b.buyer_id=? ORDER BY p.updated_at DESC',userId,userId),entries:this.s.all('SELECT e.*,p.account,p.cents FROM ledger_entries e JOIN ledger_postings p ON p.entry_id=e.id JOIN bookings b ON b.id=e.booking_id WHERE b.seller_id=? OR b.buyer_id=? ORDER BY e.created_at DESC',userId,userId),disclaimer:'Registro de operaciones; no es una billetera ni un comprobante fiscal. Neto y disponibilidad reales según Mercado Pago.'};}
 exportUser(userId){return {format:'intera-personal-export',version:5,exportedAt:new Date(this.s.now()).toISOString(),profile:{...this.safeUser(this.user(userId)),email:this.user(userId).email},consents:this.s.all('SELECT version,document_hash,accepted_at FROM consents WHERE user_id=?',userId),orders:this.bootstrap(userId).bookings.map(b=>this.details(userId,b.id)),finances:this.finances(userId),reports:this.s.all('SELECT * FROM reports WHERE user_id=?',userId)};}
}
