import {ensure,AppError} from './domain/errors.mjs';
import {id,hash,randomToken,pkce,seal,unseal} from './security.mjs';
import {toCents,commissionFor} from './domain/pricing.mjs';
const money=value=>value===undefined||value===null?null:toCents(value);
export class Payments {
 constructor(store,market,legal,config,gateway){this.s=store;this.market=market;this.legal=legal;this.c=config;this.gateway=gateway;this.locks=new Map();this.s.run("UPDATE attempts SET status='UNKNOWN' WHERE status='CREATING'");}
 async lock(key,fn){const prev=this.locks.get(key)||Promise.resolve();const p=prev.catch(()=>{}).then(fn);this.locks.set(key,p);try{return await p;}finally{if(this.locks.get(key)===p)this.locks.delete(key);}}
 async accessToken(userId){return this.lock('token:'+userId,async()=>{const a=this.s.one('SELECT * FROM seller_accounts WHERE user_id=?',userId);ensure(a&&a.mode===this.c.mode,409,'CONNECT_MP','El prestador debe conectar Mercado Pago.');const t=unseal(a.encrypted_tokens,this.c.encryptionKey,`${this.c.mode}:${userId}`);if(a.expires_at>this.s.now()+300000)return t.access_token;const r=await this.gateway.refresh(t.refresh_token);if(this.c.mode==='mock')r.user_id=a.mp_user_id;this.storeTokens(userId,r,a.mp_user_id);if(a.status==='PAUSED')this.s.run("UPDATE seller_accounts SET status='PAUSED' WHERE user_id=?",userId);return r.access_token;});}
 storeTokens(uid,t,expectedId=null){ensure(typeof t.access_token==='string'&&typeof t.refresh_token==='string'&&t.user_id!==undefined&&t.live_mode===(this.c.mode==='live')&&Number.isFinite(t.expires_in)&&t.expires_in>0,502,'OAUTH_RESPONSE','La autorización no corresponde al ambiente esperado.');const mpId=String(t.user_id);if(expectedId)ensure(mpId===String(expectedId),409,'OAUTH_ACCOUNT','Se esperaba la misma cuenta de Mercado Pago.');const prev=this.s.one('SELECT * FROM seller_accounts WHERE user_id=?',uid);ensure(!prev||prev.mp_user_id===mpId,409,'ACCOUNT_CHANGE','No se puede cambiar de cuenta de cobro sin reconciliar el historial con el operador.');const other=this.s.one('SELECT user_id FROM seller_accounts WHERE mp_user_id=? AND user_id<>?',mpId,uid);ensure(!other,409,'ACCOUNT_LINKED','La cuenta de Mercado Pago ya está vinculada a otro perfil.');const ciphertext=seal({access_token:t.access_token,refresh_token:t.refresh_token},this.c.encryptionKey,`${this.c.mode}:${uid}`);this.s.run('INSERT INTO seller_accounts VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET encrypted_tokens=excluded.encrypted_tokens,expires_at=excluded.expires_at,status=excluded.status,updated_at=excluded.updated_at',uid,mpId,ciphertext,this.s.now()+t.expires_in*1000,'CONNECTED',this.c.mode,this.s.now());this.s.audit(uid,'MP_ACCOUNT_LINKED',uid,{mpUserId:mpId,mode:this.c.mode});}
 mockConnect(uid){ensure(this.c.mode==='mock',404,'NOT_FOUND','No disponible.');this.market.operate(uid);const mpId=String(9000000+parseInt(hash(uid).slice(0,10),16));this.storeTokens(uid,{access_token:'mock-'+uid,refresh_token:'mock-refresh-'+uid,user_id:mpId,expires_in:180*86400,live_mode:false});return {connected:true,simulated:true};}
 beginOAuth(uid,sessionHash){this.market.operate(uid);ensure(this.c.mode!=='mock'&&this.c.mpClientId&&this.c.mpClientSecret,503,'MP_NOT_CONFIGURED','Configurá la aplicación de Mercado Pago en el servidor antes de vincular cuentas.');const state=randomToken(),stateHash=hash(state),p=pkce();this.s.run('INSERT INTO oauth_states VALUES(?,?,?,?,?)',stateHash,uid,sessionHash,seal(p.verifier,this.c.encryptionKey,'oauth:'+stateHash),this.s.now()+600000);return {url:this.gateway.authorizationUrl(state,p.challenge)};}
 async finishOAuth(uid,sessionHash,state,code){ensure(typeof state==='string'&&state.length<150&&typeof code==='string'&&code.length<1000,400,'OAUTH_STATE','Autorización inválida.');const h=hash(state);const row=this.s.tx(()=>{const r=this.s.one('SELECT * FROM oauth_states WHERE state_hash=?',h);ensure(r&&r.user_id===uid&&r.session_hash===sessionHash&&r.expires_at>this.s.now(),400,'OAUTH_STATE','La vinculación venció o pertenece a otra sesión.');this.s.run('DELETE FROM oauth_states WHERE state_hash=?',h);return r;});this.market.operate(uid);const result=await this.gateway.exchangeCode(code,unseal(row.encrypted_verifier,this.c.encryptionKey,'oauth:'+h));const me=await this.gateway.me(result.access_token);ensure(String(me.id)===String(result.user_id)&&me.site_id==='MLA',409,'MP_COUNTRY','Vinculá una cuenta Mercado Pago de Argentina.');this.storeTokens(uid,result);return {connected:true};}
 pauseConnection(uid){this.market.user(uid);this.s.run("UPDATE seller_accounts SET status='PAUSED',updated_at=? WHERE user_id=?",this.s.now(),uid);this.s.audit(uid,'MP_NEW_PAYMENTS_PAUSED',uid);return {paused:true,notice:'Se deshabilitan nuevos cobros. Se conservan credenciales cifradas para conciliar y devolver operaciones anteriores. La autorización se puede revocar también desde Mercado Pago.'};}
 async checkout(uid,bid,input){return this.lock('checkout:'+bid,async()=>{this.market.operate(uid);const b=this.market.getBooking(uid,bid);ensure(b.buyer_id===uid,403,'ROLE','Solo el solicitante puede pagar.');ensure(input.accept===true&&input.termsHash===this.legal.document.hash,428,'CHECKOUT_ACCEPTANCE','Confirmá el precio y las condiciones antes de pagar.');ensure(b.status==='ACCEPTED'&&['UNPAID','CHECKOUT_CREATED','PENDING','REJECTED'].includes(b.payment_status)&&b.payment_deadline>this.s.now(),409,'CHECKOUT_STATE','La orden ya no admite iniciar un pago.');this.market.operate(b.seller_id);const account=this.market.assertConnection(b.seller_id);ensure(!this.market.blocked(uid,b.seller_id),403,'BLOCKED','Estas cuentas no pueden operar.');this.market.assertSlot(b);
  const prev=this.s.one('SELECT * FROM attempts WHERE booking_id=?',bid);if(prev){ensure(prev.status==='READY'&&prev.checkout_url&&prev.expires_at>this.s.now(),409,'CHECKOUT_RECONCILE','La creación del checkout está pendiente de conciliación. No se generará otro cobro.');return {checkoutUrl:prev.checkout_url,attemptId:prev.id,simulated:this.c.mode==='mock'};}
  const token=await this.accessToken(b.seller_id);const a={id:id(),booking_id:bid,external_ref:id(),mp_seller_id:account.mp_user_id,expires_at:Math.min(this.s.now()+3600000,b.payment_deadline)};
  this.s.run('INSERT INTO attempts(id,booking_id,external_ref,mp_seller_id,status,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)',a.id,bid,a.external_ref,a.mp_seller_id,'CREATING',a.expires_at,this.s.now(),this.s.now());let p;
  try{p=await this.gateway.createPreference(token,b,a,this.market.user(uid).email);}catch(e){this.s.run("UPDATE attempts SET status='UNKNOWN',updated_at=? WHERE id=?",this.s.now(),a.id);this.s.audit(uid,'CHECKOUT_UNKNOWN',bid,{attemptId:a.id,code:e.code||'NETWORK'});throw e;}
  this.s.tx(()=>{this.s.run("UPDATE attempts SET status='READY',preference_id=?,checkout_url=?,updated_at=? WHERE id=?",p.id,p.checkoutUrl,this.s.now(),a.id);this.s.run("UPDATE bookings SET payment_status='CHECKOUT_CREATED',updated_at=? WHERE id=? AND status='ACCEPTED'",this.s.now(),bid);this.s.audit(uid,'CHECKOUT_CREATED',bid,{attemptId:a.id,preferenceId:p.id});});
  if(this.s.one('SELECT status FROM bookings WHERE id=?',bid).status!=='ACCEPTED'){this.s.enqueue('expire_preference',{attemptId:a.id},'expire-late:'+a.id);throw new AppError(409,'CANCELLED','La orden fue cancelada mientras se creaba el checkout.');}
  return {checkoutUrl:p.checkoutUrl,attemptId:a.id,simulated:this.c.mode==='mock'};
 });}
 async reconcilePayment(paymentId,sellerId){return this.lock('payment:'+paymentId,async()=>{const token=await this.accessToken(sellerId);const p=await this.gateway.getPayment(token,paymentId);ensure(String(p.id)===String(paymentId),502,'PAYMENT_ID','La respuesta no corresponde al pago consultado.');const {a,b}=this.validatePayment(sellerId,p);if(this.c.mode!=='mock'){const pref=await this.gateway.attestCheckoutPayment(token,p,a,b);if(a.status==='UNKNOWN'){this.s.run("UPDATE attempts SET status='READY',preference_id=?,checkout_url=?,updated_at=? WHERE id=? AND status='UNKNOWN'",pref.id,pref.checkoutUrl,this.s.now(),a.id);this.s.audit('mercadopago','CHECKOUT_RECOVERED',b.id,{preferenceId:pref.id});}}return this.applyPayment(sellerId,p);});}
 validatePayment(sellerId,p){const a=this.s.one('SELECT * FROM attempts WHERE external_ref=?',String(p.external_reference||''));ensure(a,409,'PAYMENT_REFERENCE','El pago no corresponde a una orden de esta plataforma.');const b=this.s.one('SELECT * FROM bookings WHERE id=?',a.booking_id);ensure(b.seller_id===sellerId&&String(p.collector_id)===a.mp_seller_id,409,'PAYMENT_COLLECTOR','El pago corresponde a otro prestador.');ensure(p.live_mode===(this.c.mode==='live'),409,'PAYMENT_MODE','El pago corresponde a otro ambiente.');ensure(p.currency_id==='ARS'&&toCents(p.transaction_amount)===b.gross_cents,409,'PAYMENT_AMOUNT','El importe o moneda no coincide con lo contratado.');ensure(!p.metadata?.booking_id||p.metadata.booking_id===b.id,409,'PAYMENT_METADATA','La referencia de la orden no coincide.');ensure(!p.metadata?.attempt_id||p.metadata.attempt_id===a.id,409,'PAYMENT_METADATA','La referencia del intento no coincide.');if(p.application_id!==undefined&&p.application_id!==null&&this.c.mpClientId)ensure(String(p.application_id)===this.c.mpClientId,409,'PAYMENT_APPLICATION','Aplicación de pago no coincidente.');ensure(!p.payer?.id||String(p.payer.id)!==String(p.collector_id),409,'PAYMENT_SELF','No se admite un pago a la propia cuenta.');
  const types=['pending','in_process','authorized','approved','rejected','cancelled','refunded','in_mediation','charged_back'];ensure(types.includes(p.status),409,'PAYMENT_STATUS','Estado de pago no reconocido.');
  const fees=Array.isArray(p.fee_details)?p.fee_details:[];const application=fees.filter(f=>['application_fee','marketplace_fee'].includes(f.type));const commission=p.application_fee!==undefined?money(p.application_fee):(application.length?application.reduce((sum,f)=>sum+toCents(f.amount),0):null);ensure(commission===null||commission===b.commission_cents,409,'PAYMENT_COMMISSION','La comisión informada difiere del 5% pactado. Requiere revisión.');
  const processor=fees.filter(f=>f.type==='mercadopago_fee');const processorCents=processor.length?processor.reduce((sum,f)=>sum+toCents(f.amount),0):null;
  const refunded=toCents(p.transaction_amount_refunded??0);ensure(refunded<=b.gross_cents,409,'REFUND_AMOUNT','Devolución inconsistente.');const providerUpdated=Date.parse(p.date_last_updated);ensure(Number.isFinite(providerUpdated),409,'PAYMENT_DATE','Falta la fecha de actualización del pago.');
  const net=money(p.transaction_details?.net_received_amount);ensure(net===null||net<=b.gross_cents,409,'PAYMENT_NET','Neto informado inconsistente.');return {a,b,commission,processorCents,refunded,providerUpdated,net};
 }
 journal(b,p,key,kind,gross,fee){if(!gross)return;const eid=id();const result=this.s.run('INSERT OR IGNORE INTO ledger_entries VALUES(?,?,?,?,?,?)',eid,key,b.id,String(p.id),kind,this.s.now());if(!result.changes)return;this.s.run('INSERT INTO ledger_postings(entry_id,account,cents) VALUES(?,?,?)',eid,'MP_SERVICE_GROSS',gross);this.s.run('INSERT INTO ledger_postings(entry_id,account,cents) VALUES(?,?,?)',eid,'INTERA_COMMISSION',-fee);this.s.run('INSERT INTO ledger_postings(entry_id,account,cents) VALUES(?,?,?)',eid,'SELLER_BEFORE_MP_COSTS',-(gross-fee));ensure(this.s.one('SELECT SUM(cents) AS balance FROM ledger_postings WHERE entry_id=?',eid).balance===0,500,'LEDGER_INVARIANT','Registro contable inconsistente.');}
 paymentSummary(bid){const b=this.s.one('SELECT * FROM bookings WHERE id=?',bid);const p=b.primary_payment_id?this.s.one('SELECT * FROM payments WHERE id=?',b.primary_payment_id):null;if(!p)return;const states={pending:'PENDING',in_process:'PENDING',authorized:'PENDING',approved:'APPROVED',rejected:'REJECTED',cancelled:'CANCELLED',refunded:'REFUNDED',in_mediation:'MEDIATION',charged_back:'CHARGED_BACK'};let state=states[p.status]||'PAYMENT_REVIEW';if(p.status==='approved'&&p.refunded_cents>0)state='PARTIALLY_REFUNDED';if(p.refunded_cents===p.amount_cents)state='REFUNDED';const pending=this.s.one("SELECT id FROM refunds WHERE payment_id=? AND status IN ('REQUESTED','PROCESSING','SUBMITTED')",p.id);if(pending&&state!=='CHARGED_BACK')state='REFUND_PENDING';const duplicate=this.s.one("SELECT id FROM payments WHERE booking_id=? AND id<>? AND status='approved' AND refunded_cents<amount_cents",bid,p.id);if(duplicate)state='PAYMENT_REVIEW';this.s.run('UPDATE bookings SET payment_status=?,updated_at=? WHERE id=?',state,this.s.now(),bid);}
 applyPayment(sellerId,p){return this.s.tx(()=>{
  const {a,b,commission,processorCents,refunded,providerUpdated,net}=this.validatePayment(sellerId,p);const pid=String(p.id),prev=this.s.one('SELECT * FROM payments WHERE id=?',pid);ensure(!prev||prev.attempt_id===a.id,409,'PAYMENT_BOUND','El pago ya está asociado a otra orden.');if(prev&&(providerUpdated<prev.provider_updated_at||refunded<prev.refunded_cents))return {ignored:true};ensure(!prev||prev.status!=='charged_back'||(p.status==='charged_back'&&refunded===prev.refunded_cents),409,'PAYMENT_TERMINAL_REVIEW','Cambio de estado después de contracargo: requiere conciliación operativa explícita.');
  this.s.run('INSERT INTO payments(id,attempt_id,booking_id,status,status_detail,amount_cents,refunded_cents,commission_reported_cents,processor_fee_cents,net_reported_cents,release_status,release_date,provider_updated_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,status_detail=excluded.status_detail,refunded_cents=excluded.refunded_cents,commission_reported_cents=excluded.commission_reported_cents,processor_fee_cents=excluded.processor_fee_cents,net_reported_cents=excluded.net_reported_cents,release_status=excluded.release_status,release_date=excluded.release_date,provider_updated_at=excluded.provider_updated_at,updated_at=excluded.updated_at',pid,a.id,b.id,p.status,String(p.status_detail||'').slice(0,100),b.gross_cents,refunded,commission,processorCents,net,String(p.money_release_status||'unreported'),p.money_release_date||null,providerUpdated,this.s.now());
  const economic=['approved','refunded','charged_back'].includes(p.status)||refunded>0;
  if(economic){this.journal(b,p,'approved:'+pid,'PAYMENT_APPROVED',b.gross_cents,b.commission_cents);if(!b.primary_payment_id)this.s.run('UPDATE bookings SET primary_payment_id=? WHERE id=?',pid,b.id);}
  if(refunded>(prev?.refunded_cents||0)){const old=prev?.refunded_cents||0;this.journal(b,p,`refund:${pid}:${refunded}`,'PAYMENT_REFUNDED',-(refunded-old),-(commissionFor(refunded)-commissionFor(old)));}
  if(p.status==='charged_back'){const remaining=b.gross_cents-refunded;this.journal(b,p,'chargeback:'+pid,'CHARGEBACK',-remaining,-(b.commission_cents-commissionFor(refunded)));}
  const submitted=this.s.all("SELECT * FROM refunds WHERE payment_id=? AND status='SUBMITTED' ORDER BY created_at",pid);const knownTotal=this.s.one("SELECT COALESCE(SUM(amount_cents),0) AS n FROM refunds WHERE payment_id=? AND status IN ('SUBMITTED','COMPLETED')",pid).n;
  for(const r of submitted){const reported=p.refunds?.some(v=>String(v.id)===r.mp_refund_id&&(!v.status||v.status==='approved'));if(reported||refunded>=knownTotal)this.s.run("UPDATE refunds SET status='COMPLETED',updated_at=? WHERE id=?",this.s.now(),r.id);}
  const current=this.s.one('SELECT * FROM bookings WHERE id=?',b.id);
  if(p.status==='approved'&&refunded<b.gross_cents){
    const duplicate=current.primary_payment_id&&current.primary_payment_id!==pid;
    let reason=null;
    if(duplicate)reason='Devolución automática de un segundo pago aprobado para la misma orden.';
    else if(current.status==='CANCELLED')reason='Devolución por pago confirmado después de cancelar la orden.';
    else if(current.parent_id&&this.s.one('SELECT status FROM bookings WHERE id=?',current.parent_id)?.status==='CANCELLED')reason='Devolución de una ampliación de un servicio cancelado.';
    else if(current.status==='ACCEPTED'){try{this.market.assertSlot(current);}catch{reason='Devolución por conflicto de horario al confirmar un pago demorado.';this.s.run("UPDATE bookings SET status='CANCELLED',cancel_reason=? WHERE id=?",reason,b.id);}}
    if(reason){const pending=this.s.one("SELECT COALESCE(SUM(amount_cents),0) AS n FROM refunds WHERE payment_id=? AND status IN ('REQUESTED','PROCESSING','SUBMITTED')",pid).n;const amount=b.gross_cents-refunded-pending;if(amount>0)this.market.requestRefund(pid,amount,reason,'system');}
  }
  if(!economic&&!b.primary_payment_id)this.s.run('UPDATE bookings SET payment_status=? WHERE id=?',p.status==='rejected'?'REJECTED':'PENDING',b.id);
  this.paymentSummary(b.id);this.s.audit('mercadopago','PAYMENT_RECONCILED',b.id,{paymentId:pid,status:p.status,refundedCents:refunded,releaseStatus:p.money_release_status||'unreported'});return {bookingId:b.id,paymentId:pid,status:p.status};
 });}
 async reconcileBooking(bid){const a=this.s.one('SELECT * FROM attempts WHERE booking_id=?',bid);if(!a)return {count:0};const b=this.s.one('SELECT * FROM bookings WHERE id=?',bid);const token=await this.accessToken(b.seller_id);const list=await this.gateway.searchPayments(token,a.external_ref);for(const p of list)await this.reconcilePayment(String(p.id),b.seller_id);this.s.run('UPDATE attempts SET next_reconcile=? WHERE id=?',this.s.now()+(this.s.one('SELECT primary_payment_id FROM bookings WHERE id=?',bid).primary_payment_id?3600000:60000),a.id);return {count:list.length};}
 async executeRefund(rid){return this.lock('refund:'+rid,async()=>{const r=this.s.one('SELECT * FROM refunds WHERE id=?',rid);ensure(r,404,'REFUND','Reembolso no encontrado.');if(r.status==='COMPLETED')return {complete:true};const b=this.s.one('SELECT * FROM bookings WHERE id=?',r.booking_id);const token=await this.accessToken(b.seller_id);if(r.status!=='SUBMITTED'){this.s.run("UPDATE refunds SET status='PROCESSING',updated_at=? WHERE id=?",this.s.now(),rid);const response=await this.gateway.refund(token,r.payment_id,r.amount_cents,r.idempotency_key);ensure(response.id&&String(response.payment_id)===r.payment_id&&toCents(response.amount)===r.amount_cents&&response.status==='approved',502,'REFUND_UNCONFIRMED','La devolución todavía no tiene confirmación verificable.');this.s.run("UPDATE refunds SET status='SUBMITTED',mp_refund_id=?,updated_at=? WHERE id=?",String(response.id),this.s.now(),rid);}await this.reconcilePayment(r.payment_id,b.seller_id);return {status:this.s.one('SELECT status FROM refunds WHERE id=?',rid).status};});}
 async expirePreference(aid){const a=this.s.one('SELECT * FROM attempts WHERE id=?',aid);if(!a?.preference_id)return;const b=this.s.one('SELECT * FROM bookings WHERE id=?',a.booking_id);const token=await this.accessToken(b.seller_id);await this.gateway.expirePreference(token,a.preference_id);await this.reconcileBooking(b.id);}
}
